/**
 * @file config_ui.h
 * @brief Config Portal UI HTML — AiPiClaw SoftAP 配置三步向导 SPA
 * @version 2.0
 * @date 2026-05-15
 *
 * @copyright Copyright (c) 2026 AI-Thinker
 *
 * @note HTTP API 端点:
 *   POST /api/wifi/scan      — 触发 WiFi 扫描
 *   GET  /api/wifi/scan      — 获取扫描结果 JSON
 *   POST /api/wifi/connect   — 连接 WiFi (body: {ssid, password})
 *   GET  /api/wifi/status    — WiFi 连接状态
 *   POST /api/llm/config     — 设置 LLM 配置
 *   GET  /api/llm/config     — 获取当前 LLM 配置
 *   POST /api/apply          — 应用配置并重启
 *
 * 内嵌 C 字符串, 零外部依赖, 350+ 行 HTML/CSS/JS.
 * 生成方式: scripts/convert_html_to_c.py
 */

#ifndef __CONFIG_UI_H
#define __CONFIG_UI_H

/**
 * @brief 配置门户 SPA 页面 HTML（三步向导）
 *
 * Step 1 — WiFi 扫描 + 选择 SSID + 密码 + 连接
 * Step 2 — LLM Provider / Model / API Key 配置
 * Step 3 — 配置摘要 + 保存并启动 → 自动切换聊天界面
 */
static const char CONFIG_UI_HTML[] =
    "     1|<!DOCTYPE html>\n"
    "     2|<!--\n"
    "     3|  =============================================================\n"
    "     4|  AiPiClaw Config Portal — SoftAP 配置门户 SPA 三步向导\n"
    "     5|  =============================================================\n"
    "     6|  用途: 新机首次配置 WiFi + LLM 的 Web 引导页面\n"
    "     7|  访问: http://192.168.4.1 (设备 SoftAP IP)\n"
    "     8|  API 基础路径: /api/\n"
    "     9|  依赖: 零外部依赖, 纯 HTML + CSS + JS ~300行\n"
    "    10|  作者: 安信可科技 Ai-Thinker\n"
    "    11|  =============================================================\n"
    "    12|-->\n"
    "    13|<html lang=\"zh-CN\">\n"
    "    14|<head>\n"
    "    15|<meta charset=\"UTF-8\">\n"
    "    16|<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
    "    17|<title>AiPiClaw 设置</title>\n"
    "    18|<style>\n"
    "    19|/* ===== 1. 全局重置 ===== */\n"
    "    20|*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    "    21|html,body{height:100%}\n"
    "    22|body{\n"
    "    23|  font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",\"Noto Sans SC\",sans-serif;\n"
    "    24|  background:#000;color:#ddd;\n"
    "    25|  display:flex;flex-direction:column;align-items:center\n"
    "    26|}\n"
    "    27|\n"
    "    28|/* ===== 2. 顶栏 ===== */\n"
    "    29|#topbar{\n"
    "    30|  width:100%;max-width:520px;\n"
    "    31|  display:flex;align-items:center;justify-content:space-between;\n"
    "    32|  padding:14px 20px 0\n"
    "    33|}\n"
    "    34|#brand{font-size:17px;font-weight:600;color:#eee;letter-spacing:.3px}\n"
    "    35|#brand span{color:#4a9eff} /* AiPi 蓝 */\n"
    "    36|.steps-indicator{font-size:12px;color:#555}\n"
    "    37|.steps-indicator .active{color:#4a9eff;font-weight:600}\n"
    "    38|\n"
    "    39|/* ===== 3. 内容区 ===== */\n"
    "    40|#container{width:100%;max-width:520px;flex:1;padding:20px;overflow-y:auto}\n"
    "    41|.step{display:none}\n"
    "    42|.step.active{display:block}\n"
    "    43|.step h2{font-size:16px;font-weight:500;color:#eee;margin-bottom:16px}\n"
    "    44|.step h2 .num{display:inline-flex;align-items:center;justify-content:center;\n"
    "    45|  width:22px;height:22px;border-radius:50%;background:#4a9eff;color:#fff;\n"
    "    46|  font-size:12px;margin-right:8px;vertical-align:middle}\n"
    "    47|\n"
    "    48|/* ===== 4. 表单控件 ===== */\n"
    "    49|label{display:block;font-size:13px;color:#888;margin-bottom:4px;margin-top:14px}\n"
    "    50|label:first-child{margin-top:0}\n"
    "    51|input,select{\n"
    "    52|  width:100%;padding:12px 14px;background:#1a1a1a;border:1px solid #333;\n"
    "    53|  border-radius:10px;color:#ddd;font-size:14px;outline:none;transition:.2s\n"
    "    54|}\n"
    "    55|input:focus,select:focus{border-color:#4a9eff;box-shadow:0 0 0 2px rgba(74,158,255,.15)}\n"
    "    56|select{cursor:pointer;appearance:none;\n"
    "    57|  background-image:url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='%23555'%3E%3Cpath d='M7 10l5 5 5-5z'/%3E%3C/svg%3E\");\n"
    "    58|  background-repeat:no-repeat;background-position:right 12px center;padding-right:32px\n"
    "    59|}\n"
    "    60|input::placeholder{color:#555}\n"
    "    61|input[type=\"password\"]{letter-spacing:2px}\n"
    "    62|\n"
    "    63|/* ===== 5. 按钮 ===== */\n"
    "    64|.btn{\n"
    "    65|  width:100%;padding:12px;border:none;border-radius:10px;font-size:15px;\n"
    "    66|  font-weight:500;cursor:pointer;transition:.2s;display:flex;align-items:center;\n"
    "    67|  justify-content:center;gap:6px;margin-top:16px\n"
    "    68|}\n"
    "    69|.btn:disabled{opacity:.4;cursor:not-allowed}\n"
    "    70|.btn-primary{background:#4a9eff;color:#fff}\n"
    "    71|.btn-primary:hover:not(:disabled){background:#3b82f6}\n"
    "    72|.btn-secondary{background:#1a1a1a;color:#aaa;border:1px solid #333}\n"
    "    73|.btn-secondary:hover:not(:disabled){background:#222;border-color:#4a9eff;color:#ddd}\n"
    "    74|.btn-success{background:#22c55e;color:#fff}\n"
    "    75|.btn-success:hover:not(:disabled){background:#16a34a}\n"
    "    76|\n"
    "    77|/* ===== 6. WiFi 扫描列表 ===== */\n"
    "    78|#scan-status{font-size:12px;color:#666;margin-top:10px}\n"
    "    79|#ap-list{margin-top:10px;display:flex;flex-direction:column;gap:6px;max-height:260px;overflow-y:auto}\n"
    "    80|.ap-card{\n"
    "    81|  display:flex;align-items:center;gap:10px;\n"
    "    82|  padding:10px 14px;background:#111;border:1px solid #222;border-radius:10px;\n"
    "    83|  cursor:pointer;transition:.2s\n"
    "    84|}\n"
    "    85|.ap-card:hover{border-color:#333;background:#181818}\n"
    "    86|.ap-card.selected{border-color:#4a9eff;background:rgba(74,158,255,.08)}\n"
    "    87|.ap-card .icon{flex-shrink:0;color:#666;font-size:14px}\n"
    "    88|.ap-card .info{flex:1;min-width:0}\n"
    "    89|.ap-card .info .ssid{font-size:14px;color:#ddd;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n"
    "    90|.ap-card .info .meta{font-size:11px;color:#555;margin-top:2px}\n"
    "    91|.ap-card .rssi{flex-shrink:0;font-size:11px;color:#555;text-align:right;min-width:40px}\n"
    "    92|\n"
    "    93|/* ===== 7. 状态消息 ===== */\n"
    "    94|.msg{margin-top:12px;padding:10px 14px;border-radius:8px;font-size:13px;display:none}\n"
    "    95|.msg.show{display:block}\n"
    "    96|.msg.success{background:rgba(34,197,94,.1);border:1px solid rgba(34,197,94,.2);color:#4ade80}\n"
    "    97|.msg.error{background:rgba(239,68,68,.1);border:1px solid rgba(239,68,68,.2);color:#f87171}\n"
    "    98|.msg.info{background:rgba(74,158,255,.1);border:1px solid rgba(74,158,255,.2);color:#60a5fa}\n"
    "    99|\n"
    "   100|/* ===== 8. 步骤3 — 配置摘要 ===== */\n"
    "   101|.summary-card{\n"
    "   102|  background:#111;border:1px solid #222;border-radius:12px;padding:16px;margin-bottom:10px\n"
    "   103|}\n"
    "   104|.summary-card .row{display:flex;justify-content:space-between;padding:6px 0;font-size:13px}\n"
    "   105|.summary-card .row .lbl{color:#666}\n"
    "   106|.summary-card .row .val{color:#ddd}\n"
    "   107|\n"
    "   108|/* ===== 9. 转换到聊天的过渡动画 ===== */\n"
    "   109|.transition-screen{\n"
    "   110|  display:none;position:fixed;top:0;left:0;width:100%;height:100%;\n"
    "   111|  background:#000;z-index:100;\n"
    "   112|  flex-direction:column;align-items:center;justify-content:center;gap:16px\n"
    "   113|}\n"
    "   114|.transition-screen.show{display:flex}\n"
    "   115|.transition-screen .spinner{width:36px;height:36px;border:3px solid #222;border-top-color:#4a9eff;border-radius:50%;animation:spin .8s linear infinite}\n"
    "   116|@keyframes spin{to{transform:rotate(360deg)}}\n"
    "   117|.transition-screen .text{font-size:14px;color:#555}\n"
    "   118|\n"
    "   119|/* ===== 10. 滚动条 ===== */\n"
    "   120|#ap-list::-webkit-scrollbar{width:4px}\n"
    "   121|#ap-list::-webkit-scrollbar-track{background:transparent}\n"
    "   122|#ap-list::-webkit-scrollbar-thumb{background:#222;border-radius:4px}\n"
    "   123|/* 移动端额外间距 */\n"
    "   124|@media(max-width:400px){#container{padding:16px}}\n"
    "   125|</style>\n"
    "   126|</head>\n"
    "   127|<body>\n"
    "   128|\n"
    "   129|<div id=\"topbar\">\n"
    "   130|  <div id=\"brand\"><span>AiPi</span>Claw</div>\n"
    "   131|  <div class=\"steps-indicator\" id=\"step-indicator\">1 / 3</div>\n"
    "   132|</div>\n"
    "   133|\n"
    "   134|<div id=\"container\">\n"
    "   135|\n"
    "   136|<!-- ===== Step 1: WiFi 配置 ===== -->\n"
    "   137|<div class=\"step active\" id=\"step1\">\n"
    "   138|  <h2><span class=\"num\">1</span>选择 WiFi 网络</h2>\n"
    "   139|  <button class=\"btn btn-secondary\" id=\"scan-btn\" onclick=\"scanWifi()\">📡 扫描 WiFi</button>\n"
    "   140|  <div id=\"scan-status\"></div>\n"
    "   141|  <div id=\"ap-list\"></div>\n"
    "   142|  <label>WiFi 密码</label>\n"
    "   143|  <input type=\"password\" id=\"wifi-pwd\" placeholder=\"输入密码\" autocomplete=\"off\">\n"
    "   144|  <button class=\"btn btn-primary\" id=\"connect-btn\" onclick=\"connectWifi()\" disabled>连接 WiFi</button>\n"
    "   145|  <div class=\"msg\" id=\"wifi-msg\"></div>\n"
    "   146|</div>\n"
    "   147|\n"
    "   148|<!-- ===== Step 2: LLM 配置 ===== -->\n"
    "   149|<div class=\"step\" id=\"step2\">\n"
    "   150|  <h2><span class=\"num\">2</span>配置 AI 服务</h2>\n"
    "   151|  <label>API 提供商</label>\n"
    "   152|  <select id=\"llm-provider\">\n"
    "   153|    <option value=\"minimax\">MiniMax</option>\n"
    "   154|    <option value=\"deepseek\">DeepSeek</option>\n"
    "   155|    <option value=\"openai\">OpenAI</option>\n"
    "   156|    <option value=\"anthropic\">Anthropic</option>\n"
    "   157|  </select>\n"
    "   158|  <label>模型名称</label>\n"
    "   159|  <input type=\"text\" id=\"llm-model\" value=\"MiniMax-M2.5\" placeholder=\"如 MiniMax-M2.5\">\n"
    "   160|  <label>API Key</label>\n"
    "   161|  <input type=\"password\" id=\"llm-key\" placeholder=\"输入 API Key\" autocomplete=\"off\">\n"
    "   162|  <button class=\"btn btn-primary\" id=\"llm-save-btn\" onclick=\"saveLLM()\">💾 保存配置</button>\n"
    "   163|  <div class=\"msg\" id=\"llm-msg\"></div>\n"
    "   164|</div>\n"
    "   165|\n"
    "   166|<!-- ===== Step 3: 完成 & 启动 ===== -->\n"
    "   167|<div class=\"step\" id=\"step3\">\n"
    "   168|  <h2><span class=\"num\">3</span>确认并启动</h2>\n"
    "   169|  <div class=\"summary-card\" id=\"summary-wifi\">\n"
    "   170|    <div class=\"row\"><span class=\"lbl\">WiFi</span><span class=\"val\" id=\"summary-ssid\">—</span></div>\n"
    "   171|  </div>\n"
    "   172|  <div class=\"summary-card\" id=\"summary-llm\">\n"
    "   173|    <div class=\"row\"><span class=\"lbl\">提供商</span><span class=\"val\" id=\"summary-provider\">—</span></div>\n"
    "   174|    <div class=\"row\"><span class=\"lbl\">模型</span><span class=\"val\" id=\"summary-model\">—</span></div>\n"
    "   175|    <div class=\"row\"><span class=\"lbl\">API Key</span><span class=\"val\" id=\"summary-key\">—</span></div>\n"
    "   176|  </div>\n"
    "   177|  <button class=\"btn btn-success\" id=\"apply-btn\" onclick=\"applyAndStart()\">🚀 保存并启动</button>\n"
    "   178|  <div class=\"msg\" id=\"apply-msg\"></div>\n"
    "   179|</div>\n"
    "   180|\n"
    "   181|</div><!-- /container -->\n"
    "   182|\n"
    "   183|<!-- 转换到聊天界面的过渡动画 -->\n"
    "   184|<div class=\"transition-screen\" id=\"transition\">\n"
    "   185|  <div class=\"spinner\"></div>\n"
    "   186|  <div class=\"text\">正在连接设备...</div>\n"
    "   187|</div>\n"
    "   188|\n"
    "   189|<script>\n"
    "   190|/* =========================================================\n"
    "   191|   AiPiClaw Config Portal — 三步向导 JS\n"
    "   192|   =========================================================\n"
    "   193|   依赖: 无\n"
    "   194|   接口: 7个 REST API 端点 (详见文件头)\n"
    "   195|   流程: Step1 WiFi → Step2 LLM → Step3 Apply → Chat\n"
    "   196|   ========================================================= */\n"
    "   197|\n"
    "   198|// ---- 全局状态 ----\n"
    "   199|let state = {\n"
    "   200|  step: 1,\n"
    "   201|  selectedSSID: '',\n"
    "   202|  ssid: '',\n"
    "   203|  pwd: '',\n"
    "   204|  provider: 'minimax',\n"
    "   205|  model: 'MiniMax-M2.5',\n"
    "   206|  key: '',\n"
    "   207|  scanning: false,\n"
    "   208|  connecting: false\n"
    "   209|};\n"
    "   210|\n"
    "   211|// ---- 步骤切换 ----\n"
    "   212|function goToStep(n) {\n"
    "   213|  document.querySelectorAll('.step').forEach(el => el.classList.remove('active'));\n"
    "   214|  document.getElementById('step' + n).classList.add('active');\n"
    "   215|  state.step = n;\n"
    "   216|  document.getElementById('step-indicator').textContent = n + ' / 3';\n"
    "   217|}\n"
    "   218|\n"
    "   219|// ---- 工具: 显示消息 ----\n"
    "   220|function showMsg(id, type, text) {\n"
    "   221|  const el = document.getElementById(id);\n"
    "   222|  el.className = 'msg show ' + type;\n"
    "   223|  el.textContent = text;\n"
    "   224|}\n"
    "   225|function hideMsg(id) {\n"
    "   226|  document.getElementById(id).className = 'msg';\n"
    "   227|  document.getElementById(id).textContent = '';\n"
    "   228|}\n"
    "   229|\n"
    "   230|// ---- Step 1: WiFi 扫描 ----\n"
    "   231|function scanWifi() {\n"
    "   232|  if (state.scanning) return;\n"
    "   233|  state.scanning = true;\n"
    "   234|  const btn = document.getElementById('scan-btn');\n"
    "   235|  btn.disabled = true;\n"
    "   236|  btn.textContent = '⏳ 扫描中...';\n"
    "   237|  document.getElementById('scan-status').textContent = '';\n"
    "   238|  document.getElementById('ap-list').innerHTML = '';\n"
    "   239|\n"
    "   240|  // POST 触发扫描\n"
    "   241|  fetch('/api/wifi/scan', { method: 'POST' })\n"
    "   242|    .then(r => r.json())\n"
    "   243|    .then(d => {\n"
    "   244|      // 轮询扫描结果\n"
    "   245|      return new Promise((resolve, reject) => {\n"
    "   246|        const poll = () => {\n"
    "   247|          fetch('/api/wifi/scan')\n"
    "   248|            .then(r => r.json())\n"
    "   249|            .then(res => {\n"
    "   250|              if (res.ssids && res.ssids.length > 0) {\n"
    "   251|                resolve(res);\n"
    "   252|              } else {\n"
    "   253|                setTimeout(poll, 500);\n"
    "   254|              }\n"
    "   255|            })\n"
    "   256|            .catch(reject);\n"
    "   257|        };\n"
    "   258|        setTimeout(poll, 500);\n"
    "   259|      });\n"
    "   260|    })\n"
    "   261|    .then(res => renderAPList(res.ssids))\n"
    "   262|    .catch(err => {\n"
    "   263|      showMsg('wifi-msg', 'error', '扫描失败: ' + err.message);\n"
    "   264|    })\n"
    "   265|    .finally(() => {\n"
    "   266|      state.scanning = false;\n"
    "   267|      btn.disabled = false;\n"
    "   268|      btn.textContent = '📡 重新扫描';\n"
    "   269|    });\n"
    "   270|}\n"
    "   271|\n"
    "   272|function renderAPList(ssids) {\n"
    "   273|  const list = document.getElementById('ap-list');\n"
    "   274|  list.innerHTML = '';\n"
    "   275|  if (!ssids || ssids.length === 0) {\n"
    "   276|    document.getElementById('scan-status').textContent = '未发现 WiFi 网络';\n"
    "   277|    return;\n"
    "   278|  }\n"
    "   279|  document.getElementById('scan-status').textContent = '找到 ' + ssids.length + ' 个网络';\n"
    "   280|  ssids.forEach(ap => {\n"
    "   281|    const card = document.createElement('div');\n"
    "   282|    card.className = 'ap-card';\n"
    "   283|    // WiFi 信号图标: 根据信号强度选不同格数\n"
    "   284|    const bars = ap.rssi > -50 ? 3 : ap.rssi > -70 ? 2 : 1;\n"
    "   285|    card.innerHTML =\n"
    "   286|      '<div class=\"icon\">' + '📶' + '</div>' +\n"
    "   287|      '<div class=\"info\"><div class=\"ssid\">' + escHtml(ap.ssid) + '</div>' +\n"
    "   288|      '<div class=\"meta\">' + (ap.auth || 'WPA2') + '</div></div>' +\n"
    "   289|      '<div class=\"rssi\">' + ap.rssi + ' dBm</div>';\n"
    "   290|    card.onclick = function() {\n"
    "   291|      document.querySelectorAll('.ap-card').forEach(c => c.classList.remove('selected'));\n"
    "   292|      card.classList.add('selected');\n"
    "   293|      state.selectedSSID = ap.ssid;\n"
    "   294|      state.ssid = ap.ssid;\n"
    "   295|      document.getElementById('connect-btn').disabled = false;\n"
    "   296|      document.getElementById('wifi-pwd').focus();\n"
    "   297|    };\n"
    "   298|    list.appendChild(card);\n"
    "   299|  });\n"
    "   300|}\n"
    "   301|\n"
    "   302|// ---- Step 1: WiFi 连接 ----\n"
    "   303|function connectWifi() {\n"
    "   304|  if (!state.ssid) { showMsg('wifi-msg', 'error', '请先选择一个 WiFi 网络'); return; }\n"
    "   305|  if (state.connecting) return;\n"
    "   306|  state.connecting = true;\n"
    "   307|  state.pwd = document.getElementById('wifi-pwd').value;\n"
    "   308|  const btn = document.getElementById('connect-btn');\n"
    "   309|  btn.disabled = true;\n"
    "   310|  btn.textContent = '⏳ 连接中...';\n"
    "   311|  hideMsg('wifi-msg');\n"
    "   312|\n"
    "   313|  fetch('/api/wifi/connect', {\n"
    "   314|    method: 'POST',\n"
    "   315|    headers: { 'Content-Type': 'application/json' },\n"
    "   316|    body: JSON.stringify({ ssid: state.ssid, password: state.pwd })\n"
    "   317|  })\n"
    "   318|  .then(r => r.json())\n"
    "   319|  .then(d => {\n"
    "   320|    showMsg('wifi-msg', 'success', 'WiFi 凭据已保存，正在连接...');\n"
    "   321|    // 轮询连接状态\n"
    "   322|    return pollWifiStatus();\n"
    "   323|  })\n"
    "   324|  .then(status => {\n"
    "   325|    if (status.status === 'connected') {\n"
    "   326|      showMsg('wifi-msg', 'success', '✅ WiFi 已连接 — ' + (status.ip || ''));\n"
    "   327|      setTimeout(() => goToStep(2), 800);\n"
    "   328|    } else {\n"
    "   329|      showMsg('wifi-msg', 'info', 'WiFi 凭据已保存，连接可能需要 10-15 秒');\n"
    "   330|      setTimeout(() => goToStep(2), 1500);\n"
    "   331|    }\n"
    "   332|  })\n"
    "   333|  .catch(err => {\n"
    "   334|    showMsg('wifi-msg', 'error', '连接失败: ' + err.message);\n"
    "   335|    btn.disabled = false;\n"
    "   336|    btn.textContent = '连接 WiFi';\n"
    "   337|    state.connecting = false;\n"
    "   338|  });\n"
    "   339|}\n"
    "   340|\n"
    "   341|function pollWifiStatus(maxRetries) {\n"
    "   342|  maxRetries = maxRetries || 15;\n"
    "   343|  return new Promise((resolve, reject) => {\n"
    "   344|    let tries = 0;\n"
    "   345|    const poll = () => {\n"
    "   346|      tries++;\n"
    "   347|      fetch('/api/wifi/status')\n"
    "   348|        .then(r => r.json())\n"
    "   349|        .then(s => {\n"
    "   350|          if (s.status === 'connected') resolve(s);\n"
    "   351|          else if (tries >= maxRetries) resolve(s);  // 超时也返回\n"
    "   352|          else setTimeout(poll, 800);\n"
    "   353|        })\n"
    "   354|        .catch(() => {\n"
    "   355|          if (tries >= maxRetries) reject(new Error('状态查询超时'));\n"
    "   356|          else setTimeout(poll, 800);\n"
    "   357|        });\n"
    "   358|    };\n"
    "   359|    setTimeout(poll, 500);\n"
    "   360|  });\n"
    "   361|}\n"
    "   362|\n"
    "   363|// ---- Step 2: LLM 配置 ----\n"
    "   364|function saveLLM() {\n"
    "   365|  state.provider = document.getElementById('llm-provider').value;\n"
    "   366|  state.model = document.getElementById('llm-model').value || state.model;\n"
    "   367|  state.key = document.getElementById('llm-key').value;\n"
    "   368|  const btn = document.getElementById('llm-save-btn');\n"
    "   369|  btn.disabled = true;\n"
    "   370|  btn.textContent = '⏳ 保存中...';\n"
    "   371|  hideMsg('llm-msg');\n"
    "   372|\n"
    "   373|  fetch('/api/llm/config', {\n"
    "   374|    method: 'POST',\n"
    "   375|    headers: { 'Content-Type': 'application/json' },\n"
    "   376|    body: JSON.stringify({ provider: state.provider, model: state.model, api_key: state.key })\n"
    "   377|  })\n"
    "   378|  .then(r => r.json())\n"
    "   379|  .then(d => {\n"
    "   380|    showMsg('llm-msg', 'success', '✅ AI 配置已保存');\n"
    "   381|    setTimeout(() => goToStep(3), 800);\n"
    "   382|  })\n"
    "   383|  .catch(err => {\n"
    "   384|    showMsg('llm-msg', 'error', '保存失败: ' + err.message);\n"
    "   385|    btn.disabled = false;\n"
    "   386|    btn.textContent = '💾 保存配置';\n"
    "   387|  });\n"
    "   388|}\n"
    "   389|\n"
    "   390|// ---- Step 3: 应用 & 启动 ----\n"
    "   391|function applyAndStart() {\n"
    "   392|  // 填充摘要\n"
    "   393|  document.getElementById('summary-ssid').textContent = state.ssid || '—';\n"
    "   394|  document.getElementById('summary-provider').textContent = state.provider || '—';\n"
    "   395|  document.getElementById('summary-model').textContent = state.model || '—';\n"
    "   396|  document.getElementById('summary-key').textContent = state.key ? '••••' + state.key.slice(-4) : '—';\n"
    "   397|\n"
    "   398|  const btn = document.getElementById('apply-btn');\n"
    "   399|  btn.disabled = true;\n"
    "   400|  btn.textContent = '⏳ 正在应用...';\n"
    "   401|  hideMsg('apply-msg');\n"
    "   402|\n"
    "   403|  fetch('/api/apply', { method: 'POST' })\n"
    "   404|    .then(r => r.json())\n"
    "   405|    .then(d => {\n"
    "   406|      showMsg('apply-msg', 'success', '✅ 配置已应用！正在切换到聊天模式...');\n"
    "   407|      // 显示过渡动画\n"
    "   408|      document.getElementById('transition').classList.add('show');\n"
    "   409|      // 等待设备重启 + WS 服务器启动\n"
    "   410|      setTimeout(switchToChat, 8000);\n"
    "   411|    })\n"
    "   412|    .catch(err => {\n"
    "   413|      showMsg('apply-msg', 'error', '应用失败: ' + err.message);\n"
    "   414|      btn.disabled = false;\n"
    "   415|      btn.textContent = '🚀 保存并启动';\n"
    "   416|    });\n"
    "   417|}\n"
    "   418|\n"
    "   419|// ---- 切换到聊天界面 ----\n"
    "   420|function switchToChat() {\n"
    "   421|  const host = '192.168.4.1';\n"
    "   422|  const wsUrl = 'ws://' + host + ':18789';\n"
    "   423|  document.querySelector('#transition .text').textContent = '连接聊天服务...';\n"
    "   424|\n"
    "   425|  // 尝试连接 WebSocket\n"
    "   426|  let retries = 0;\n"
    "   427|  const maxRetries = 20;\n"
    "   428|  function tryConnect() {\n"
    "   429|    const ws = new WebSocket(wsUrl);\n"
    "   430|    const t = setTimeout(function() {\n"
    "   431|      ws.onclose = null;\n"
    "   432|      ws.close();\n"
    "   433|      retries++;\n"
    "   434|      if (retries < maxRetries) {\n"
    "   435|        document.querySelector('#transition .text').textContent =\n"
    "   436|          '连接中 (' + retries + '/' + maxRetries + ')...';\n"
    "   437|        setTimeout(tryConnect, 1500);\n"
    "   438|      } else {\n"
    "   439|        document.querySelector('#transition .text').textContent =\n"
    "   440|          '连接超时，请刷新页面重试';\n"
    "   441|      }\n"
    "   442|    }, 3000);\n"
    "   443|    ws.onopen = function() {\n"
    "   444|      clearTimeout(t);\n"
    "   445|      // 切换到聊天界面: 重定向到根路径\n"
    "   446|      window.location.href = 'http://' + host + '/';\n"
    "   447|    };\n"
    "   448|    ws.onclose = function() {\n"
    "   449|      clearTimeout(t);\n"
    "   450|    };\n"
    "   451|  }\n"
    "   452|  tryConnect();\n"
    "   453|}\n"
    "   454|\n"
    "   455|// ---- 工具: HTML 转义 ----\n"
    "   456|function escHtml(s) {\n"
    "   457|  if (!s) return '';\n"
    "   458|  const m = {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'};\n"
    "   459|  return String(s).replace(/[&<>\"']/g, c => m[c]);\n"
    "   460|}\n"
    "   461|\n"
    "   462|// ---- 自动加载已有配置 ----\n"
    "   463|function loadExistingConfig() {\n"
    "   464|  fetch('/api/llm/config')\n"
    "   465|    .then(r => r.json())\n"
    "   466|    .then(d => {\n"
    "   467|      if (d.provider) {\n"
    "   468|        document.getElementById('llm-provider').value = d.provider;\n"
    "   469|        state.provider = d.provider;\n"
    "   470|      }\n"
    "   471|      if (d.model) {\n"
    "   472|        document.getElementById('llm-model').value = d.model;\n"
    "   473|        state.model = d.model;\n"
    "   474|      }\n"
    "   475|      if (d.api_key && d.api_key.length > 0) {\n"
    "   476|        document.getElementById('llm-key').placeholder = '已配置，可留空保持不变';\n"
    "   477|      }\n"
    "   478|    })\n"
    "   479|    .catch(() => {});\n"
    "   480|  // 也检查 WiFi 状态\n"
    "   481|  fetch('/api/wifi/status')\n"
    "   482|    .then(r => r.json())\n"
    "   483|    .then(s => {\n"
    "   484|      if (s.ssid) {\n"
    "   485|        state.ssid = s.ssid;\n"
    "   486|        state.selectedSSID = s.ssid;\n"
    "   487|      }\n"
    "   488|    })\n"
    "   489|    .catch(() => {});\n"
    "   490|}\n"
    "   491|\n"
    "   492|// ---- 初始化 ----\n"
    "   493|loadExistingConfig();\n"
    "   494|</script>\n"
    "   495|</body>\n"
    "   496|</html>\n"
    "   497|"
;

#define CONFIG_UI_HTML_LEN (sizeof(CONFIG_UI_HTML) - 1)

#endif /* __CONFIG_UI_H */