#ifndef _CONFIG_UI_H_
#define _CONFIG_UI_H_

/**
 * @brief Embedded Web UI — auto-generated from config_ui.html
 * @note Do not edit manually. Regenerate with scripts/embed_html.py
 */
static const char CONFIG_UI_HTML[] =
    "<!DOCTYPE html>\n"
    "<!--\n"
    "  =============================================================\n"
    "  AiPiClaw Config Portal — SoftAP 配置门户 SPA 三步向导\n"
    "  =============================================================\n"
    "  用途: 新机首次配置 WiFi + LLM 的 Web 引导页面\n"
    "  访问: http://192.168.4.1 (设备 SoftAP IP)\n"
    "  API 基础路径: /api/\n"
    "  依赖: 零外部依赖, 纯 HTML + CSS + JS ~300行\n"
    "  作者: 安信可科技 Ai-Thinker\n"
    "  =============================================================\n"
    "-->\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
    "<title>AiPiClaw 设置</title>\n"
    "<style>\n"
    "/* ===== 1. 全局重置 ===== */\n"
    "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    "html,body{height:100%}\n"
    "body{\n"
    "  font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",\"Noto Sans SC\",sans-serif;\n"
    "  background:#000;color:#ddd;\n"
    "  display:flex;flex-direction:column;align-items:center\n"
    "}\n"
    "\n"
    "/* ===== 2. 顶栏 ===== */\n"
    "#topbar{\n"
    "  width:100%;max-width:520px;\n"
    "  display:flex;align-items:center;justify-content:space-between;\n"
    "  padding:14px 20px 0\n"
    "}\n"
    "#brand{font-size:17px;font-weight:600;color:#eee;letter-spacing:.3px}\n"
    "#brand span{color:#4a9eff} /* AiPi 蓝 */\n"
    ".steps-indicator{font-size:12px;color:#555}\n"
    ".steps-indicator .active{color:#4a9eff;font-weight:600}\n"
    "\n"
    "/* ===== 3. 内容区 ===== */\n"
    "#container{width:100%;max-width:520px;flex:1;padding:20px;overflow-y:auto}\n"
    ".step{display:none}\n"
    ".step.active{display:block}\n"
    ".step h2{font-size:16px;font-weight:500;color:#eee;margin-bottom:16px}\n"
    ".step h2 .num{display:inline-flex;align-items:center;justify-content:center;\n"
    "  width:22px;height:22px;border-radius:50%;background:#4a9eff;color:#fff;\n"
    "  font-size:12px;margin-right:8px;vertical-align:middle}\n"
    "\n"
    "/* ===== 4. 表单控件 ===== */\n"
    "label{display:block;font-size:13px;color:#888;margin-bottom:4px;margin-top:14px}\n"
    "label:first-child{margin-top:0}\n"
    "input,select{\n"
    "  width:100%;padding:12px 14px;background:#1a1a1a;border:1px solid #333;\n"
    "  border-radius:10px;color:#ddd;font-size:14px;outline:none;transition:.2s\n"
    "}\n"
    "input:focus,select:focus{border-color:#4a9eff;box-shadow:0 0 0 2px rgba(74,158,255,.15)}\n"
    "select{cursor:pointer;appearance:none;\n"
    "  background-image:url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='%23555'%3E%3Cpath d='M7 10l5 5 5-5z'/%3E%3C/svg%3E\");\n"
    "  background-repeat:no-repeat;background-position:right 12px center;padding-right:32px\n"
    "}\n"
    "input::placeholder{color:#555}\n"
    "input[type=\"password\"]{letter-spacing:2px}\n"
    "\n"
    "/* ===== 5. 按钮 ===== */\n"
    ".btn{\n"
    "  width:100%;padding:12px;border:none;border-radius:10px;font-size:15px;\n"
    "  font-weight:500;cursor:pointer;transition:.2s;display:flex;align-items:center;\n"
    "  justify-content:center;gap:6px;margin-top:16px\n"
    "}\n"
    ".btn:disabled{opacity:.4;cursor:not-allowed}\n"
    ".btn-primary{background:#4a9eff;color:#fff}\n"
    ".btn-primary:hover:not(:disabled){background:#3b82f6}\n"
    ".btn-secondary{background:#1a1a1a;color:#aaa;border:1px solid #333}\n"
    ".btn-secondary:hover:not(:disabled){background:#222;border-color:#4a9eff;color:#ddd}\n"
    ".btn-success{background:#22c55e;color:#fff}\n"
    ".btn-success:hover:not(:disabled){background:#16a34a}\n"
    "\n"
    "/* ===== 6. WiFi 扫描列表 ===== */\n"
    "#scan-status{font-size:12px;color:#666;margin-top:10px}\n"
    "#ap-list{margin-top:10px;display:flex;flex-direction:column;gap:6px;max-height:260px;overflow-y:auto}\n"
    ".ap-card{\n"
    "  display:flex;align-items:center;gap:10px;\n"
    "  padding:10px 14px;background:#111;border:1px solid #222;border-radius:10px;\n"
    "  cursor:pointer;transition:.2s\n"
    "}\n"
    ".ap-card:hover{border-color:#333;background:#181818}\n"
    ".ap-card.selected{border-color:#4a9eff;background:rgba(74,158,255,.08)}\n"
    ".ap-card .icon{flex-shrink:0;color:#666;font-size:14px}\n"
    ".ap-card .info{flex:1;min-width:0}\n"
    ".ap-card .info .ssid{font-size:14px;color:#ddd;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n"
    ".ap-card .info .meta{font-size:11px;color:#555;margin-top:2px}\n"
    ".ap-card .rssi{flex-shrink:0;font-size:11px;color:#555;text-align:right;min-width:40px}\n"
    "\n"
    "/* ===== 7. 状态消息 ===== */\n"
    ".msg{margin-top:12px;padding:10px 14px;border-radius:8px;font-size:13px;display:none}\n"
    ".msg.show{display:block}\n"
    ".msg.success{background:rgba(34,197,94,.1);border:1px solid rgba(34,197,94,.2);color:#4ade80}\n"
    ".msg.error{background:rgba(239,68,68,.1);border:1px solid rgba(239,68,68,.2);color:#f87171}\n"
    ".msg.info{background:rgba(74,158,255,.1);border:1px solid rgba(74,158,255,.2);color:#60a5fa}\n"
    "\n"
    "/* ===== 8. 步骤3 — 配置摘要 ===== */\n"
    ".summary-card{\n"
    "  background:#111;border:1px solid #222;border-radius:12px;padding:16px;margin-bottom:10px\n"
    "}\n"
    ".summary-card .row{display:flex;justify-content:space-between;padding:6px 0;font-size:13px}\n"
    ".summary-card .row .lbl{color:#666}\n"
    ".summary-card .row .val{color:#ddd}\n"
    "\n"
    "/* ===== 9. 转换到聊天的过渡动画 ===== */\n"
    ".transition-screen{\n"
    "  display:none;position:fixed;top:0;left:0;width:100%;height:100%;\n"
    "  background:#000;z-index:100;\n"
    "  flex-direction:column;align-items:center;justify-content:center;gap:16px\n"
    "}\n"
    ".transition-screen.show{display:flex}\n"
    ".transition-screen .spinner{width:36px;height:36px;border:3px solid #222;border-top-color:#4a9eff;border-radius:50%;animation:spin .8s linear infinite}\n"
    "@keyframes spin{to{transform:rotate(360deg)}}\n"
    ".transition-screen .text{font-size:14px;color:#555}\n"
    "\n"
    "/* ===== 10. 滚动条 ===== */\n"
    "#ap-list::-webkit-scrollbar{width:4px}\n"
    "#ap-list::-webkit-scrollbar-track{background:transparent}\n"
    "#ap-list::-webkit-scrollbar-thumb{background:#222;border-radius:4px}\n"
    "/* 移动端额外间距 */\n"
    "@media(max-width:400px){#container{padding:16px}}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<div id=\"topbar\">\n"
    "  <div id=\"brand\"><span>AiPi</span>Claw</div>\n"
    "  <div class=\"steps-indicator\" id=\"step-indicator\">1 / 3</div>\n"
    "</div>\n"
    "\n"
    "<div id=\"container\">\n"
    "\n"
    "<!-- ===== Step 1: WiFi 配置 ===== -->\n"
    "<div class=\"step active\" id=\"step1\">\n"
    "  <h2><span class=\"num\">1</span>选择 WiFi 网络</h2>\n"
    "  <button class=\"btn btn-secondary\" id=\"scan-btn\" onclick=\"scanWifi()\">📡 扫描 WiFi</button>\n"
    "  <div id=\"scan-status\"></div>\n"
    "  <div id=\"ap-list\"></div>\n"
    "  <label>WiFi 密码</label>\n"
    "  <input type=\"password\" id=\"wifi-pwd\" placeholder=\"输入密码\" autocomplete=\"off\">\n"
    "  <button class=\"btn btn-primary\" id=\"connect-btn\" onclick=\"connectWifi()\" disabled>连接 WiFi</button>\n"
    "  <div class=\"msg\" id=\"wifi-msg\"></div>\n"
    "</div>\n"
    "\n"
    "<!-- ===== Step 2: LLM 配置 ===== -->\n"
    "<div class=\"step\" id=\"step2\">\n"
    "  <h2><span class=\"num\">2</span>配置 AI 服务</h2>\n"
    "  <label>API 提供商</label>\n"
    "  <select id=\"llm-provider\">\n"
    "    <option value=\"minimax\">MiniMax</option>\n"
    "    <option value=\"deepseek\">DeepSeek</option>\n"
    "    <option value=\"openai\">OpenAI</option>\n"
    "    <option value=\"anthropic\">Anthropic</option>\n"
    "  </select>\n"
    "  <label>模型名称</label>\n"
    "  <input type=\"text\" id=\"llm-model\" value=\"MiniMax-M2.5\" placeholder=\"如 MiniMax-M2.5\">\n"
    "  <label>API Key</label>\n"
    "  <input type=\"password\" id=\"llm-key\" placeholder=\"输入 API Key\" autocomplete=\"off\">\n"
    "  <button class=\"btn btn-primary\" id=\"llm-save-btn\" onclick=\"saveLLM()\">💾 保存配置</button>\n"
    "  <div class=\"msg\" id=\"llm-msg\"></div>\n"
    "</div>\n"
    "\n"
    "<!-- ===== Step 3: 完成 & 启动 ===== -->\n"
    "<div class=\"step\" id=\"step3\">\n"
    "  <h2><span class=\"num\">3</span>确认并启动</h2>\n"
    "  <div class=\"summary-card\" id=\"summary-wifi\">\n"
    "    <div class=\"row\"><span class=\"lbl\">WiFi</span><span class=\"val\" id=\"summary-ssid\">—</span></div>\n"
    "  </div>\n"
    "  <div class=\"summary-card\" id=\"summary-llm\">\n"
    "    <div class=\"row\"><span class=\"lbl\">提供商</span><span class=\"val\" id=\"summary-provider\">—</span></div>\n"
    "    <div class=\"row\"><span class=\"lbl\">模型</span><span class=\"val\" id=\"summary-model\">—</span></div>\n"
    "    <div class=\"row\"><span class=\"lbl\">API Key</span><span class=\"val\" id=\"summary-key\">—</span></div>\n"
    "  </div>\n"
    "  <button class=\"btn btn-success\" id=\"apply-btn\" onclick=\"applyAndStart()\">🚀 保存并启动</button>\n"
    "  <div class=\"msg\" id=\"apply-msg\"></div>\n"
    "</div>\n"
    "\n"
    "</div><!-- /container -->\n"
    "\n"
    "<!-- 转换到聊天界面的过渡动画 -->\n"
    "<div class=\"transition-screen\" id=\"transition\">\n"
    "  <div class=\"spinner\"></div>\n"
    "  <div class=\"text\">正在连接设备...</div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "/* =========================================================\n"
    "   AiPiClaw Config Portal — 三步向导 JS\n"
    "   =========================================================\n"
    "   依赖: 无\n"
    "   接口: 7个 REST API 端点 (详见文件头)\n"
    "   流程: Step1 WiFi → Step2 LLM → Step3 Apply → Chat\n"
    "   ========================================================= */\n"
    "\n"
    "// ---- 全局状态 ----\n"
    "let state = {\n"
    "  step: 1,\n"
    "  selectedSSID: '',\n"
    "  ssid: '',\n"
    "  pwd: '',\n"
    "  provider: 'minimax',\n"
    "  model: 'MiniMax-M2.5',\n"
    "  key: '',\n"
    "  scanning: false,\n"
    "  connecting: false\n"
    "};\n"
    "\n"
    "// ---- 步骤切换 ----\n"
    "function goToStep(n) {\n"
    "  document.querySelectorAll('.step').forEach(el => el.classList.remove('active'));\n"
    "  document.getElementById('step' + n).classList.add('active');\n"
    "  state.step = n;\n"
    "  document.getElementById('step-indicator').textContent = n + ' / 3';\n"
    "}\n"
    "\n"
    "// ---- 工具: 显示消息 ----\n"
    "function showMsg(id, type, text) {\n"
    "  const el = document.getElementById(id);\n"
    "  el.className = 'msg show ' + type;\n"
    "  el.textContent = text;\n"
    "}\n"
    "function hideMsg(id) {\n"
    "  document.getElementById(id).className = 'msg';\n"
    "  document.getElementById(id).textContent = '';\n"
    "}\n"
    "\n"
    "// ---- Step 1: WiFi 扫描 ----\n"
    "function scanWifi() {\n"
    "  if (state.scanning) return;\n"
    "  state.scanning = true;\n"
    "  const btn = document.getElementById('scan-btn');\n"
    "  btn.disabled = true;\n"
    "  btn.textContent = '⏳ 扫描中...';\n"
    "  document.getElementById('scan-status').textContent = '';\n"
    "  document.getElementById('ap-list').innerHTML = '';\n"
    "\n"
    "  // POST 触发扫描\n"
    "  fetch('/api/wifi/scan', { method: 'POST' })\n"
    "    .then(r => r.json())\n"
    "    .then(d => {\n"
    "      // 轮询扫描结果\n"
    "      return new Promise((resolve, reject) => {\n"
    "        const poll = () => {\n"
    "          fetch('/api/wifi/scan')\n"
    "            .then(r => r.json())\n"
    "            .then(res => {\n"
    "              if (res.ssids && res.ssids.length > 0) {\n"
    "                resolve(res);\n"
    "              } else {\n"
    "                setTimeout(poll, 500);\n"
    "              }\n"
    "            })\n"
    "            .catch(reject);\n"
    "        };\n"
    "        setTimeout(poll, 500);\n"
    "      });\n"
    "    })\n"
    "    .then(res => renderAPList(res.ssids))\n"
    "    .catch(err => {\n"
    "      showMsg('wifi-msg', 'error', '扫描失败: ' + err.message);\n"
    "    })\n"
    "    .finally(() => {\n"
    "      state.scanning = false;\n"
    "      btn.disabled = false;\n"
    "      btn.textContent = '📡 重新扫描';\n"
    "    });\n"
    "}\n"
    "\n"
    "function renderAPList(ssids) {\n"
    "  const list = document.getElementById('ap-list');\n"
    "  list.innerHTML = '';\n"
    "  if (!ssids || ssids.length === 0) {\n"
    "    document.getElementById('scan-status').textContent = '未发现 WiFi 网络';\n"
    "    return;\n"
    "  }\n"
    "  document.getElementById('scan-status').textContent = '找到 ' + ssids.length + ' 个网络';\n"
    "  ssids.forEach(ap => {\n"
    "    const card = document.createElement('div');\n"
    "    card.className = 'ap-card';\n"
    "    // WiFi 信号图标: 根据信号强度选不同格数\n"
    "    const bars = ap.rssi > -50 ? 3 : ap.rssi > -70 ? 2 : 1;\n"
    "    card.innerHTML =\n"
    "      '<div class=\"icon\">' + '📶' + '</div>' +\n"
    "      '<div class=\"info\"><div class=\"ssid\">' + escHtml(ap.ssid) + '</div>' +\n"
    "      '<div class=\"meta\">' + (ap.auth || 'WPA2') + '</div></div>' +\n"
    "      '<div class=\"rssi\">' + ap.rssi + ' dBm</div>';\n"
    "    card.onclick = function() {\n"
    "      document.querySelectorAll('.ap-card').forEach(c => c.classList.remove('selected'));\n"
    "      card.classList.add('selected');\n"
    "      state.selectedSSID = ap.ssid;\n"
    "      state.ssid = ap.ssid;\n"
    "      document.getElementById('connect-btn').disabled = false;\n"
    "      document.getElementById('wifi-pwd').focus();\n"
    "    };\n"
    "    list.appendChild(card);\n"
    "  });\n"
    "}\n"
    "\n"
    "// ---- Step 1: WiFi 连接 ----\n"
    "function connectWifi() {\n"
    "  if (!state.ssid) { showMsg('wifi-msg', 'error', '请先选择一个 WiFi 网络'); return; }\n"
    "  if (state.connecting) return;\n"
    "  state.connecting = true;\n"
    "  state.pwd = document.getElementById('wifi-pwd').value;\n"
    "  const btn = document.getElementById('connect-btn');\n"
    "  btn.disabled = true;\n"
    "  btn.textContent = '⏳ 连接中...';\n"
    "  hideMsg('wifi-msg');\n"
    "\n"
    "  fetch('/api/wifi/connect', {\n"
    "    method: 'POST',\n"
    "    headers: { 'Content-Type': 'application/json' },\n"
    "    body: JSON.stringify({ ssid: state.ssid, password: state.pwd })\n"
    "  })\n"
    "  .then(r => r.json())\n"
    "  .then(d => {\n"
    "    showMsg('wifi-msg', 'success', 'WiFi 凭据已保存，正在连接...');\n"
    "    // 轮询连接状态\n"
    "    return pollWifiStatus();\n"
    "  })\n"
    "  .then(status => {\n"
    "    if (status.status === 'connected') {\n"
    "      showMsg('wifi-msg', 'success', '✅ WiFi 已连接 — ' + (status.ip || ''));\n"
    "      setTimeout(() => goToStep(2), 800);\n"
    "    } else {\n"
    "      showMsg('wifi-msg', 'info', 'WiFi 凭据已保存，连接可能需要 10-15 秒');\n"
    "      setTimeout(() => goToStep(2), 1500);\n"
    "    }\n"
    "  })\n"
    "  .catch(err => {\n"
    "    showMsg('wifi-msg', 'error', '连接失败: ' + err.message);\n"
    "    btn.disabled = false;\n"
    "    btn.textContent = '连接 WiFi';\n"
    "    state.connecting = false;\n"
    "  });\n"
    "}\n"
    "\n"
    "function pollWifiStatus(maxRetries) {\n"
    "  maxRetries = maxRetries || 15;\n"
    "  return new Promise((resolve, reject) => {\n"
    "    let tries = 0;\n"
    "    const poll = () => {\n"
    "      tries++;\n"
    "      fetch('/api/wifi/status')\n"
    "        .then(r => r.json())\n"
    "        .then(s => {\n"
    "          if (s.status === 'connected') resolve(s);\n"
    "          else if (tries >= maxRetries) resolve(s);  // 超时也返回\n"
    "          else setTimeout(poll, 800);\n"
    "        })\n"
    "        .catch(() => {\n"
    "          if (tries >= maxRetries) reject(new Error('状态查询超时'));\n"
    "          else setTimeout(poll, 800);\n"
    "        });\n"
    "    };\n"
    "    setTimeout(poll, 500);\n"
    "  });\n"
    "}\n"
    "\n"
    "// ---- Step 2: LLM 配置 ----\n"
    "function saveLLM() {\n"
    "  state.provider = document.getElementById('llm-provider').value;\n"
    "  state.model = document.getElementById('llm-model').value || state.model;\n"
    "  state.key = document.getElementById('llm-key').value;\n"
    "  const btn = document.getElementById('llm-save-btn');\n"
    "  btn.disabled = true;\n"
    "  btn.textContent = '⏳ 保存中...';\n"
    "  hideMsg('llm-msg');\n"
    "\n"
    "  fetch('/api/llm/config', {\n"
    "    method: 'POST',\n"
    "    headers: { 'Content-Type': 'application/json' },\n"
    "    body: JSON.stringify({ provider: state.provider, model: state.model, api_key: state.key })\n"
    "  })\n"
    "  .then(r => r.json())\n"
    "  .then(d => {\n"
    "    showMsg('llm-msg', 'success', '✅ AI 配置已保存');\n"
    "    setTimeout(() => goToStep(3), 800);\n"
    "  })\n"
    "  .catch(err => {\n"
    "    showMsg('llm-msg', 'error', '保存失败: ' + err.message);\n"
    "    btn.disabled = false;\n"
    "    btn.textContent = '💾 保存配置';\n"
    "  });\n"
    "}\n"
    "\n"
    "// ---- Step 3: 应用 & 启动 ----\n"
    "function applyAndStart() {\n"
    "  // 填充摘要\n"
    "  document.getElementById('summary-ssid').textContent = state.ssid || '—';\n"
    "  document.getElementById('summary-provider').textContent = state.provider || '—';\n"
    "  document.getElementById('summary-model').textContent = state.model || '—';\n"
    "  document.getElementById('summary-key').textContent = state.key ? '••••' + state.key.slice(-4) : '—';\n"
    "\n"
    "  const btn = document.getElementById('apply-btn');\n"
    "  btn.disabled = true;\n"
    "  btn.textContent = '⏳ 正在应用...';\n"
    "  hideMsg('apply-msg');\n"
    "\n"
    "  fetch('/api/apply', { method: 'POST' })\n"
    "    .then(r => r.json())\n"
    "    .then(d => {\n"
    "      showMsg('apply-msg', 'success', '✅ 配置已应用！正在切换到聊天模式...');\n"
    "      // 显示过渡动画\n"
    "      document.getElementById('transition').classList.add('show');\n"
    "      // 等待设备重启 + WS 服务器启动\n"
    "      setTimeout(switchToChat, 8000);\n"
    "    })\n"
    "    .catch(err => {\n"
    "      showMsg('apply-msg', 'error', '应用失败: ' + err.message);\n"
    "      btn.disabled = false;\n"
    "      btn.textContent = '🚀 保存并启动';\n"
    "    });\n"
    "}\n"
    "\n"
    "// ---- 切换到聊天界面 ----\n"
    "function switchToChat() {\n"
    "  const host = '192.168.4.1';\n"
    "  const wsUrl = 'ws://' + host + ':18789';\n"
    "  document.querySelector('#transition .text').textContent = '连接聊天服务...';\n"
    "\n"
    "  // 尝试连接 WebSocket\n"
    "  let retries = 0;\n"
    "  const maxRetries = 20;\n"
    "  function tryConnect() {\n"
    "    const ws = new WebSocket(wsUrl);\n"
    "    const t = setTimeout(function() {\n"
    "      ws.onclose = null;\n"
    "      ws.close();\n"
    "      retries++;\n"
    "      if (retries < maxRetries) {\n"
    "        document.querySelector('#transition .text').textContent =\n"
    "          '连接中 (' + retries + '/' + maxRetries + ')...';\n"
    "        setTimeout(tryConnect, 1500);\n"
    "      } else {\n"
    "        document.querySelector('#transition .text').textContent =\n"
    "          '连接超时，请刷新页面重试';\n"
    "      }\n"
    "    }, 3000);\n"
    "    ws.onopen = function() {\n"
    "      clearTimeout(t);\n"
    "      // 切换到聊天界面: 重定向到根路径\n"
    "      window.location.href = 'http://' + host + '/';\n"
    "    };\n"
    "    ws.onclose = function() {\n"
    "      clearTimeout(t);\n"
    "    };\n"
    "  }\n"
    "  tryConnect();\n"
    "}\n"
    "\n"
    "// ---- 工具: HTML 转义 ----\n"
    "function escHtml(s) {\n"
    "  if (!s) return '';\n"
    "  const m = {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'};\n"
    "  return String(s).replace(/[&<>\"']/g, c => m[c]);\n"
    "}\n"
    "\n"
    "// ---- 自动加载已有配置 ----\n"
    "function loadExistingConfig() {\n"
    "  fetch('/api/llm/config')\n"
    "    .then(r => r.json())\n"
    "    .then(d => {\n"
    "      if (d.provider) {\n"
    "        document.getElementById('llm-provider').value = d.provider;\n"
    "        state.provider = d.provider;\n"
    "      }\n"
    "      if (d.model) {\n"
    "        document.getElementById('llm-model').value = d.model;\n"
    "        state.model = d.model;\n"
    "      }\n"
    "      if (d.api_key && d.api_key.length > 0) {\n"
    "        document.getElementById('llm-key').placeholder = '已配置，可留空保持不变';\n"
    "      }\n"
    "    })\n"
    "    .catch(() => {});\n"
    "  // 也检查 WiFi 状态\n"
    "  fetch('/api/wifi/status')\n"
    "    .then(r => r.json())\n"
    "    .then(s => {\n"
    "      if (s.ssid) {\n"
    "        state.ssid = s.ssid;\n"
    "        state.selectedSSID = s.ssid;\n"
    "      }\n"
    "    })\n"
    "    .catch(() => {});\n"
    "}\n"
    "\n"
    "// ---- 初始化 ----\n"
    "loadExistingConfig();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "";

#endif /* _CONFIG_UI_H_ */
