#ifndef _CONFIG_UI_H_
#define _CONFIG_UI_H_

/**
 * @brief Embedded Web UI — auto-generated from config_ui.html
 * @note Do not edit manually. Regenerate with scripts/embed_html.py
 */
static const char CONFIG_UI_HTML[] =
    "<!DOCTYPE html>\n"
    "<!--\n"
    "  =============================================================\n"
    "  AiPiClaw Config Portal — SoftAP 配置页面（单页设计）\n"
    "  =============================================================\n"
    "  用途: 新机首次配置 WiFi + LLM 的 Web 引导页面\n"
    "  访问: http://192.168.4.1 (设备 SoftAP IP)\n"
    "  API 基础路径: /api/\n"
    "  依赖: 零外部依赖, 纯 HTML + CSS + JS\n"
    "  作者: 安信可科技 Ai-Thinker\n"
    "  =============================================================\n"
    "-->\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
    "<title>AiPiClaw 设置</title>\n"
    "<style>\n"
    "/* ===== 1. 全局重置 ===== */\n"
    "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    "html,body{height:100%}\n"
    "body{\n"
    "  font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",\"Noto Sans SC\",sans-serif;\n"
    "  background:#000;color:#ddd;\n"
    "  display:flex;flex-direction:column;align-items:center\n"
    "}\n"
    "\n"
    "/* ===== 2. 顶栏 (响应式) ===== */\n"
    "#topbar{\n"
    "  width:100%;max-width:520px;\n"
    "  display:flex;align-items:center;justify-content:space-between;\n"
    "  padding:clamp(10px,3vw,14px) clamp(14px,4vw,20px) 0\n"
    "}\n"
    "#brand{font-size:clamp(15px,4.5vw,17px);font-weight:600;color:#eee;letter-spacing:.3px}\n"
    "#brand span{color:#4a9eff}\n"
    "\n"
    "/* ===== 3. 内容区 (响应式) ===== */\n"
    "#container{width:100%;max-width:520px;flex:1;padding:clamp(14px,4vw,20px);overflow-y:auto}\n"
    "#container h2{font-size:clamp(15px,4.5vw,17px);font-weight:500;color:#eee;margin-bottom:clamp(10px,4vw,16px)}\n"
    ".section{border:1px solid #222;border-radius:12px;padding:clamp(12px,4vw,16px);margin-bottom:clamp(10px,4vw,16px)}\n"
    ".section h3{font-size:clamp(13px,3.8vw,14px);font-weight:500;color:#aaa;margin-bottom:clamp(8px,3vw,12px);display:flex;align-items:center;gap:6px}\n"
    ".section h3 .icon{font-size:clamp(14px,4vw,16px)}\n"
    "\n"
    "/* ===== 4. 表单控件 (移动端优化) ===== */\n"
    "label{display:block;font-size:clamp(12px,3.5vw,13px);color:#888;margin-bottom:4px;margin-top:clamp(10px,3vw,14px)}\n"
    "label:first-of-type{margin-top:0}\n"
    "input,select{\n"
    "  width:100%;padding:clamp(10px,3vw,14px) clamp(12px,3.5vw,14px);\n"
    "  background:#1a1a1a;border:1px solid #333;\n"
    "  border-radius:10px;color:#ddd;font-size:clamp(14px,4vw,16px);outline:none;transition:.2s;\n"
    "  -webkit-appearance:none;appearance:none\n"
    "}\n"
    "input:focus,select:focus{border-color:#4a9eff;box-shadow:0 0 0 2px rgba(74,158,255,.15)}\n"
    "select{cursor:pointer;\n"
    "  background-image:url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='%23555'%3E%3Cpath d='M7 10l5 5 5-5z'/%3E%3C/svg%3E\");\n"
    "  background-repeat:no-repeat;background-position:right 12px center;padding-right:32px\n"
    "}\n"
    "input::placeholder{color:#555;font-size:clamp(13px,3.5vw,14px)}\n"
    "input[type=\"password\"]{letter-spacing:2px}\n"
    "\n"
    "/* ===== 5. 按钮 (触摸友好 ≥44px) ===== */\n"
    ".btn{\n"
    "  width:100%;padding:12px;border:none;border-radius:10px;font-size:clamp(14px,4vw,16px);\n"
    "  font-weight:500;cursor:pointer;transition:.2s;display:flex;align-items:center;\n"
    "  justify-content:center;gap:6px;margin-top:16px;min-height:44px;-webkit-tap-highlight-color:transparent\n"
    "}\n"
    ".btn:disabled{opacity:.4;cursor:not-allowed}\n"
    ".btn-primary{background:#4a9eff;color:#fff}\n"
    ".btn-primary:hover:not(:disabled){background:#3b82f6}\n"
    ".btn-secondary{background:#1a1a1a;color:#aaa;border:1px solid #333}\n"
    ".btn-secondary:hover:not(:disabled){background:#222;border-color:#4a9eff;color:#ddd}\n"
    ".btn-success{background:#22c55e;color:#fff}\n"
    ".btn-success:hover:not(:disabled){background:#16a34a}\n"
    "\n"
    "/* ===== 6. WiFi 扫描列表 (触摸友好) ===== */\n"
    "#scan-status{font-size:clamp(11px,3vw,12px);color:#666;margin-top:10px}\n"
    "#ap-list{margin-top:10px;display:flex;flex-direction:column;gap:6px;max-height:clamp(180px,50vh,220px);overflow-y:auto}\n"
    ".ap-card{\n"
    "  display:flex;align-items:center;gap:10px;\n"
    "  padding:clamp(10px,3vw,14px);background:#111;border:1px solid #222;border-radius:10px;\n"
    "  cursor:pointer;transition:.2s;min-height:44px;-webkit-tap-highlight-color:transparent\n"
    "}\n"
    ".ap-card:hover{border-color:#333;background:#181818}\n"
    ".ap-card.selected{border-color:#4a9eff;background:rgba(74,158,255,.08)}\n"
    ".ap-card .icon{flex-shrink:0;color:#666;font-size:clamp(13px,3.5vw,14px)}\n"
    ".ap-card .info{flex:1;min-width:0}\n"
    ".ap-card .info .ssid{font-size:clamp(13px,3.8vw,14px);color:#ddd;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n"
    ".ap-card .info .meta{font-size:clamp(10px,3vw,11px);color:#555;margin-top:2px}\n"
    ".ap-card .rssi{flex-shrink:0;font-size:clamp(10px,3vw,11px);color:#555;text-align:right;min-width:40px}\n"
    "\n"
    "/* ===== 7. 状态消息 ===== */\n"
    ".msg{margin-top:12px;padding:clamp(8px,2.5vw,10px) clamp(10px,3.5vw,14px);border-radius:8px;font-size:clamp(12px,3.5vw,13px);display:none}\n"
    ".msg.show{display:block}\n"
    ".msg.success{background:rgba(34,197,94,.1);border:1px solid rgba(34,197,94,.2);color:#4ade80}\n"
    ".msg.error{background:rgba(239,68,68,.1);border:1px solid rgba(239,68,68,.2);color:#f87171}\n"
    ".msg.info{background:rgba(74,158,255,.1);border:1px solid rgba(74,158,255,.2);color:#60a5fa}\n"
    "\n"
    "/* ===== 8. 过渡动画 ===== */\n"
    ".transition-screen{\n"
    "  display:none;position:fixed;top:0;left:0;width:100%;height:100%;\n"
    "  background:#000;z-index:100;\n"
    "  flex-direction:column;align-items:center;justify-content:center;gap:16px\n"
    "}\n"
    ".transition-screen.show{display:flex}\n"
    ".transition-screen .spinner{width:36px;height:36px;border:3px solid #222;border-top-color:#4a9eff;border-radius:50%;animation:spin .8s linear infinite}\n"
    "@keyframes spin{to{transform:rotate(360deg)}}\n"
    ".transition-screen .text{font-size:14px;color:#555}\n"
    "\n"
    "/* ===== 9. 滚动条 ===== */\n"
    "#ap-list::-webkit-scrollbar{width:4px}\n"
    "#ap-list::-webkit-scrollbar-track{background:transparent}\n"
    "#ap-list::-webkit-scrollbar-thumb{background:#222;border-radius:4px}\n"
    "\n"
    "/* ===== 10. 移动端安全区域 & 防缩放 ===== */\n"
    "input,select,textarea{font-size:16px!important} /* iOS 防自动zoom */\n"
    "@media(max-width:480px){\n"
    "  #container{padding:12px}\n"
    "  #topbar{padding:10px 12px 0}\n"
    "  .section{border-radius:10px}\n"
    "}\n"
    "@media(min-width:768px){\n"
    "  #container{padding:24px}\n"
    "  body{justify-content:center}\n"
    "  #topbar{padding:18px 24px 0}\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<div id=\"topbar\">\n"
    "  <div id=\"brand\"><span>AiPi</span>Claw</div>\n"
    "</div>\n"
    "\n"
    "<div id=\"container\">\n"
    "\n"
    "<!-- ===== WiFi 配置区 ===== -->\n"
    "<div class=\"section\">\n"
    "  <h3><span class=\"icon\">📶</span>WiFi 网络</h3>\n"
    "  <button class=\"btn btn-secondary\" id=\"scan-btn\" onclick=\"scanWifi()\">📡 扫描 WiFi</button>\n"
    "  <div id=\"scan-status\"></div>\n"
    "  <div id=\"ap-list\"></div>\n"
    "  <label>WiFi 密码</label>\n"
    "  <input type=\"password\" id=\"wifi-pwd\" placeholder=\"输入密码\" autocomplete=\"off\">\n"
    "  <div class=\"msg\" id=\"wifi-msg\"></div>\n"
    "</div>\n"
    "\n"
    "<!-- ===== AI 服务配置区 ===== -->\n"
    "<div class=\"section\">\n"
    "  <h3><span class=\"icon\">🤖</span>AI 服务</h3>\n"
    "  <label>API 提供商</label>\n"
    "  <select id=\"llm-provider\">\n"
    "    <option value=\"minimax\">MiniMax</option>\n"
    "    <option value=\"deepseek\">DeepSeek</option>\n"
    "    <option value=\"openai\">OpenAI</option>\n"
    "    <option value=\"anthropic\">Anthropic</option>\n"
    "  </select>\n"
    "  <label>模型名称</label>\n"
    "  <input type=\"text\" id=\"llm-model\" value=\"MiniMax-M2.5\" placeholder=\"如 MiniMax-M2.5\">\n"
    "  <label>API Key</label>\n"
    "  <input type=\"password\" id=\"llm-key\" placeholder=\"输入 API Key\" autocomplete=\"off\">\n"
    "  <div class=\"msg\" id=\"llm-msg\"></div>\n"
    "</div>\n"
    "\n"
    "<!-- ===== 保存并启动 ===== -->\n"
    "<button class=\"btn btn-success\" id=\"apply-btn\" onclick=\"applyConfig()\">🚀 保存并启动</button>\n"
    "<div class=\"msg\" id=\"apply-msg\"></div>\n"
    "\n"
    "</div><!-- /container -->\n"
    "\n"
    "<!-- 过渡动画 -->\n"
    "<div class=\"transition-screen\" id=\"transition\">\n"
    "  <div class=\"spinner\"></div>\n"
    "  <div class=\"text\">正在连接设备...</div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "/* =========================================================\n"
    "   AiPiClaw Config Portal — 单页配置\n"
    "   =========================================================\n"
    "   依赖: 无\n"
    "   接口: 5个 REST API 端点\n"
    "   流程: 配置 WiFi + LLM → 一键保存并启动 → 切 /chat\n"
    "   ========================================================= */\n"
    "\n"
    "// ---- 全局状态 ----\n"
    "let state = {\n"
    "  selectedSSID: '',\n"
    "  ssid: '',\n"
    "  pwd: '',\n"
    "  provider: 'minimax',\n"
    "  model: 'MiniMax-M2.5',\n"
    "  key: '',\n"
    "  scanning: false,\n"
    "  saving: false\n"
    "};\n"
    "\n"
    "// ---- 工具: 显示消息 ----\n"
    "function showMsg(id, type, text) {\n"
    "  const el = document.getElementById(id);\n"
    "  el.className = 'msg show ' + type;\n"
    "  el.textContent = text;\n"
    "}\n"
    "function hideMsg(id) {\n"
    "  document.getElementById(id).className = 'msg';\n"
    "  document.getElementById(id).textContent = '';\n"
    "}\n"
    "\n"
    "// ---- WiFi 扫描 ----\n"
    "function scanWifi() {\n"
    "  if (state.scanning) return;\n"
    "  state.scanning = true;\n"
    "  const btn = document.getElementById('scan-btn');\n"
    "  btn.disabled = true;\n"
    "  btn.textContent = '⏳ 扫描中...';\n"
    "  document.getElementById('scan-status').textContent = '';\n"
    "  document.getElementById('ap-list').innerHTML = '';\n"
    "\n"
    "  fetch('/api/wifi/scan')\n"
    "    .then(r => {\n"
    "      if (!r.ok) throw new Error('HTTP ' + r.status);\n"
    "      return r.json();\n"
    "    })\n"
    "    .then(res => {\n"
    "      if (res.aps && res.aps.length > 0) {\n"
    "        renderAPList(res.aps);\n"
    "      } else {\n"
    "        document.getElementById('scan-status').textContent = '未发现 WiFi 网络';\n"
    "      }\n"
    "    })\n"
    "    .catch(err => {\n"
    "      showMsg('wifi-msg', 'error', '扫描失败: ' + err.message);\n"
    "    })\n"
    "    .finally(() => {\n"
    "      state.scanning = false;\n"
    "      btn.disabled = false;\n"
    "      btn.textContent = '📡 重新扫描';\n"
    "    });\n"
    "}\n"
    "\n"
    "function renderAPList(aps) {\n"
    "  const list = document.getElementById('ap-list');\n"
    "  list.innerHTML = '';\n"
    "  document.getElementById('scan-status').textContent = '找到 ' + aps.length + ' 个网络';\n"
    "  aps.forEach(ap => {\n"
    "    const card = document.createElement('div');\n"
    "    card.className = 'ap-card';\n"
    "    card.innerHTML =\n"
    "      '<div class=\"icon\">📶</div>' +\n"
    "      '<div class=\"info\"><div class=\"ssid\">' + escHtml(ap.ssid) + '</div>' +\n"
    "      '<div class=\"meta\">' + (ap.auth || 'WPA2') + '</div></div>' +\n"
    "      '<div class=\"rssi\">' + ap.rssi + ' dBm</div>';\n"
    "    card.onclick = function() {\n"
    "      document.querySelectorAll('.ap-card').forEach(c => c.classList.remove('selected'));\n"
    "      card.classList.add('selected');\n"
    "      state.ssid = ap.ssid;\n"
    "      document.getElementById('wifi-pwd').focus();\n"
    "    };\n"
    "    list.appendChild(card);\n"
    "  });\n"
    "}\n"
    "\n"
    "// ---- 一键保存并启动 ----\n"
    "function applyConfig() {\n"
    "  if (state.saving) return;\n"
    "\n"
    "  // 收集数据\n"
    "  state.ssid = state.ssid || document.getElementById('wifi-pwd').dataset.ssid || '';\n"
    "  state.pwd = document.getElementById('wifi-pwd').value;\n"
    "  state.provider = document.getElementById('llm-provider').value;\n"
    "  state.model = document.getElementById('llm-model').value || state.model;\n"
    "  state.key = document.getElementById('llm-key').value;\n"
    "\n"
    "  // 验证\n"
    "  if (!state.ssid) {\n"
    "    showMsg('apply-msg', 'error', '请先选择 WiFi 网络');\n"
    "    document.getElementById('scan-btn').scrollIntoView({behavior:'smooth'});\n"
    "    return;\n"
    "  }\n"
    "  if (!state.key || state.key.trim() === '') {\n"
    "    showMsg('apply-msg', 'error', '请输入 API Key');\n"
    "    document.getElementById('llm-key').focus();\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  state.saving = true;\n"
    "  const btn = document.getElementById('apply-btn');\n"
    "  btn.disabled = true;\n"
    "  btn.textContent = '⏳ 正在保存...';\n"
    "  hideMsg('apply-msg');\n"
    "\n"
    "  // 1. 保存 WiFi\n"
    "  fetch('/api/wifi/connect', {\n"
    "    method: 'POST',\n"
    "    headers: { 'Content-Type': 'application/json' },\n"
    "    body: JSON.stringify({ ssid: state.ssid, password: state.pwd })\n"
    "  })\n"
    "  .then(r => {\n"
    "    if (!r.ok) throw new Error('WiFi 保存失败: HTTP ' + r.status);\n"
    "    return r.json();\n"
    "  })\n"
    "  .then(() => {\n"
    "    // 2. 保存 LLM\n"
    "    return fetch('/api/llm/config', {\n"
    "      method: 'POST',\n"
    "      headers: { 'Content-Type': 'application/json' },\n"
    "      body: JSON.stringify({ provider: state.provider, model: state.model, api_key: state.key })\n"
    "    });\n"
    "  })\n"
    "  .then(r => {\n"
    "    if (!r.ok) throw new Error('AI 配置保存失败: HTTP ' + r.status);\n"
    "    return r.json();\n"
    "  })\n"
    "  .then(d => {\n"
    "    if (d.error) throw new Error(d.error);\n"
    "    // 3. 应用\n"
    "    return fetch('/api/apply', { method: 'POST' });\n"
    "  })\n"
    "  .then(r => {\n"
    "    if (!r.ok) throw new Error('应用失败: HTTP ' + r.status);\n"
    "    return r.json();\n"
    "  })\n"
    "  .then(() => {\n"
    "    showMsg('apply-msg', 'success', '✅ 配置已保存！正在切换到聊天...');\n"
    "    // 显示过渡动画\n"
    "    document.getElementById('transition').classList.add('show');\n"
    "    // 8 秒后尝试切换到聊天\n"
    "    setTimeout(switchToChat, 8000);\n"
    "  })\n"
    "  .catch(err => {\n"
    "    showMsg('apply-msg', 'error', err.message);\n"
    "    btn.disabled = false;\n"
    "    btn.textContent = '🚀 保存并启动';\n"
    "    state.saving = false;\n"
    "  });\n"
    "}\n"
    "\n"
    "// ---- 切换到聊天界面（auto-connect via hostname） ----\n"
    "function switchToChat() {\n"
    "  const host = window.location.hostname || '192.168.4.1';\n"
    "  const wsUrl = 'ws://' + host + ':18789';\n"
    "  document.querySelector('#transition .text').textContent = '连接聊天服务...';\n"
    "\n"
    "  let retries = 0;\n"
    "  const maxRetries = 20;\n"
    "  function tryConnect() {\n"
    "    const ws = new WebSocket(wsUrl);\n"
    "    const t = setTimeout(function() {\n"
    "      ws.onclose = null;\n"
    "      ws.close();\n"
    "      retries++;\n"
    "      if (retries < maxRetries) {\n"
    "        document.querySelector('#transition .text').textContent =\n"
    "          '连接中 (' + retries + '/' + maxRetries + ')...';\n"
    "        setTimeout(tryConnect, 1500);\n"
    "      } else {\n"
    "        document.querySelector('#transition .text').textContent =\n"
    "          '连接超时，请刷新页面重试';\n"
    "      }\n"
    "    }, 3000);\n"
    "    ws.onopen = function() {\n"
    "      clearTimeout(t);\n"
    "      window.location.href = 'http://' + host + '/chat';\n"
    "    };\n"
    "    ws.onclose = function() {\n"
    "      clearTimeout(t);\n"
    "    };\n"
    "  }\n"
    "  tryConnect();\n"
    "}\n"
    "\n"
    "// ---- 工具: HTML 转义 ----\n"
    "function escHtml(s) {\n"
    "  if (!s) return '';\n"
    "  const m = {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'};\n"
    "  return String(s).replace(/[&<>\"']/g, c => m[c]);\n"
    "}\n"
    "\n"
    "// ---- 自动加载已有配置 ----\n"
    "function loadExistingConfig() {\n"
    "  fetch('/api/llm/config')\n"
    "    .then(r => r.json())\n"
    "    .then(d => {\n"
    "      if (d.provider) {\n"
    "        document.getElementById('llm-provider').value = d.provider;\n"
    "        state.provider = d.provider;\n"
    "      }\n"
    "      if (d.model) {\n"
    "        document.getElementById('llm-model').value = d.model;\n"
    "        state.model = d.model;\n"
    "      }\n"
    "      if (d.api_key && d.api_key.length > 0) {\n"
    "        document.getElementById('llm-key').placeholder = '已配置，可留空保持不变';\n"
    "      }\n"
    "    })\n"
    "    .catch(() => {});\n"
    "  fetch('/api/wifi/status')\n"
    "    .then(r => r.json())\n"
    "    .then(s => {\n"
    "      if (s.ssid) {\n"
    "        state.ssid = s.ssid;\n"
    "      }\n"
    "    })\n"
    "    .catch(() => {});\n"
    "}\n"
    "\n"
    "// ---- 初始化 ----\n"
    "loadExistingConfig();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "";

#endif /* _CONFIG_UI_H_ */
