#ifndef _WEB_UI_H_
#define _WEB_UI_H_

/**
 * @brief Embedded Web UI — auto-generated from web_ui.html
 * @note Do not edit manually. Regenerate with scripts/embed_html.py
 */
static const char WEB_UI_HTML[] =
    "\n"
    "<!DOCTYPE html>\n"
    "<!--\n"
    "  =============================================================\n"
    "  AiPiClaw Web Chat — AiPiClaw AI Agent Web 聊天界面\n"
    "  =============================================================\n"
    "  用途: 通过 WebSocket 与 BL618 固件通信, 实现 AI 对话交互\n"
    "  连接: ws://{hostname}:18789 (自动连接)\n"
    "  协议: 纯文本帧, UTF-8 编码, 无 JSON 封装\n"
    "  依赖: 零外部依赖, 纯 HTML + CSS + JS\n"
    "  作者: 安信可科技 Ai-Thinker\n"
    "=============================================================\n"
    "-->\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
    "<title>AiPiClaw</title>\n"
    "<style>\n"
    "/* ===== 1. 全局重置 & 基础样式 ===== */\n"
    "/* 清除浏览器默认边距, 统一盒模型 */\n"
    "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    "html,body{height:100%;overflow:hidden}\n"
    "body{\n"
    "  font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",\"Noto Sans SC\",sans-serif;\n"
    "  background:#000;color:#fff;display:flex;flex-direction:column\n"
    "}\n"
    "\n"
    "/* ===== 2. 顶栏 — 品牌名 / 操作按钮 / 连接状态 ===== */\n"
    "#topbar{\n"
    "  display:flex;align-items:center;justify-content:space-between;\n"
    "  padding:10px 20px;flex-shrink:0;min-height:50px;position:relative\n"
    "}\n"
    "#brand{font-size:16px;font-weight:600;color:#eee;letter-spacing:.3px}\n"
    "#brand span{color:#4a9eff} /* AiPi 蓝色高亮 */\n"
    "\n"
    "/* 右上角功能区 */\n"
    "#topbar-right{display:flex;align-items:center;gap:10px}\n"
    "\n"
    "/* 状态指示灯 — 12px 圆点 + 发光效果 */\n"
    ".dot{width:12px;height:12px;border-radius:50%;display:inline-block;flex-shrink:0}\n"
    ".dot.green{background:#2ecc71;box-shadow:0 0 8px rgba(46,204,71,.5)}\n"
    ".dot.red{background:#e74c3c;box-shadow:0 0 8px rgba(231,76,60,.5)}\n"
    ".dot.yellow{background:#f39c12;box-shadow:0 0 8px rgba(243,156,18,.5)}\n"
    "\n"
    "/* 状态标签文字 */\n"
    "#status{display:flex;align-items:center;gap:5px;font-size:12px}\n"
    "#status-label{font-size:12px;text-transform:uppercase;letter-spacing:.5px}\n"
    "#status-label.green{color:#2ecc71}\n"
    "#status-label.red{color:#e74c3c}\n"
    "#status-label.yellow{color:#f39c12}\n"
    "\n"
    "/* 顶栏操作按钮: 48x48 触控热区, 正圆, 悬停高亮 */\n"
    ".tb-btn{\n"
    "  background:transparent;border:1px solid #222;border-radius:50%;\n"
    "  width:30px;height:30px;color:#666;cursor:pointer;font-size:12px;\n"
    "  display:flex;align-items:center;justify-content:center;transition:.2s\n"
    "}\n"
    ".tb-btn:hover{background:#111;color:#aaa;border-color:#444}\n"
    "\n"
    "/* WiFi SVG 图标 — 16x16 灰显 */\n"
    "#wifi-icon{fill:#555;width:16px;height:16px;vertical-align:middle}\n"
    "\n"
    "/* ===== 3. 主区域 ===== */\n"
    "#main{flex:1;display:flex;flex-direction:column;overflow:hidden;position:relative}\n"
    "\n"
    "/* 聊天消息滚动容器 */\n"
    "#chat-area{flex:1;overflow-y:auto;display:flex;flex-direction:column}\n"
    "/* 自动滚动到底部 */\n"
    "#chat-area::after{content:\"\";display:block;height:1px;flex-shrink:0}\n"
    "\n"
    "/* ===== 4. 滚动到底部按钮 — 浮动在右下角 ===== */\n"
    "#scroll-btn{\n"
    "  position:absolute;bottom:80px;right:20px;\n"
    "  background:#1a1a1a;border:1px solid #333;border-radius:50%;\n"
    "  width:36px;height:36px;color:#888;cursor:pointer;z-index:10;\n"
    "  display:none;align-items:center;justify-content:center;\n"
    "  transition:opacity .3s;box-shadow:0 2px 12px rgba(0,0,0,.6)\n"
    "}\n"
    "#scroll-btn.show{display:flex}\n"
    "#scroll-btn:hover{background:#222;color:#ccc}\n"
    "\n"
    "/* ===== 5. 空状态引导区 — 首次打开时显示 ===== */\n"
    "/* 包含标题 + 推荐问题卡片, 发送第一条消息后自动隐藏 */\n"
    "#empty-state{\n"
    "  display:flex;flex-direction:column;align-items:center;\n"
    "  justify-content:center;flex:1;padding:0 20px 40px\n"
    "}\n"
    "#empty-state h1{font-size:26px;font-weight:500;color:#e0e0e0;margin-bottom:6px}\n"
    "#empty-state .sub{font-size:13px;color:#555;margin-bottom:24px}\n"
    ".suggestions{display:flex;flex-direction:column;gap:8px;width:100%;max-width:360px}\n"
    ".suggestions .card{\n"
    "  background:#111;border:1px solid #222;border-radius:12px;\n"
    "  padding:12px 16px;cursor:pointer;transition:.2s;\n"
    "  display:flex;align-items:center;gap:10px;font-size:13px;color:#999\n"
    "}\n"
    ".suggestions .card:hover{background:#1a1a1a;border-color:#333;color:#ccc}\n"
    ".suggestions .card .icon{font-size:18px;flex-shrink:0}\n"
    "\n"
    "/* ===== 6. 消息气泡 — 用户/AI/系统/错误四种样式 ===== */\n"
    "/* max-width:720px 居中容器, padding 提供左右留白 */\n"
    "#messages{width:100%;max-width:720px;margin:0 auto;padding:16px 20px 8px}\n"
    ".msg{display:flex;margin-bottom:14px}\n"
    ".msg.user{justify-content:flex-end}   /* 用户气泡靠右 */\n"
    ".msg.ai{justify-content:flex-start}   /* AI 气泡靠左 */\n"
    ".msg.system{justify-content:center;margin-bottom:6px}   /* 系统提示居中 */\n"
    ".msg.error{justify-content:center;margin-bottom:6px}    /* 错误消息居中 */\n"
    "\n"
    "/* 气泡本体 */\n"
    ".bubble{\n"
    "  padding:10px 16px;border-radius:18px;font-size:14px;line-height:1.6;\n"
    "  max-width:80%;word-wrap:break-word;overflow-wrap:break-word\n"
    "}\n"
    "/* 用户气泡 — 蓝底, 右下圆角收口 */\n"
    ".msg.user .bubble{\n"
    "  background:#2a2a2a;color:#e0e0e0;border-bottom-right-radius:4px  /* 用户: 右下角收口 */\n"
    "}\n"
    "/* AI 气泡 — 深灰底, 左下圆角收口 */\n"
    ".msg.ai .bubble{\n"
    "  background:#181818;color:#ccc;border-bottom-left-radius:4px    /* AI: 左下角收口 */\n"
    "}\n"
    "/* 系统消息气泡 — 小号灰色居中 */\n"
    ".msg.system .bubble{\n"
    "  background:transparent;color:#555;font-size:12px;padding:2px 8px;max-width:100%\n"
    "}\n"
    "/* 错误消息气泡 — 红色居中 */\n"
    ".msg.error .bubble{\n"
    "  background:rgba(231,76,60,.08);border:1px solid rgba(231,76,60,.15);\n"
    "  color:#e74c3c;font-size:13px;max-width:90%\n"
    "}\n"
    "\n"
    "/* ===== 7. Markdown 渲染 ===== */\n"
    "/* AI 回复中的行内代码 / 代码块 / 链接 / 列表 */\n"
    ".bubble p{margin:0 0 6px}\n"
    ".bubble p:last-child{margin-bottom:0}\n"
    ".bubble em{font-style:italic}\n"
    ".bubble strong{font-weight:600;color:#e8e8e8}\n"
    ".bubble code{\n"
    "  background:rgba(255,255,255,.06);color:#e6c07b;padding:1px 5px;\n"
    "  border-radius:4px;font-size:13px;font-family:\"Consolas\",\"Courier New\",monospace\n"
    "}\n"
    ".bubble pre{\n"
    "  background:#0d0d0d;border:1px solid #222;border-radius:8px;\n"
    "  padding:10px 14px;margin:6px 0;overflow-x:auto;font-size:13px\n"
    "}\n"
    ".bubble pre code{background:none;padding:0;border-radius:0}\n"
    ".bubble a{color:#4a9eff;text-decoration:none}\n"
    ".bubble a:hover{text-decoration:underline}\n"
    ".bubble ul,.bubble ol{padding-left:20px;margin:4px 0}\n"
    ".bubble li{margin:2px 0}\n"
    "\n"
    "/* ===== 8. 打字动画 — AI 思考中三点弹跳 + 状态文案 ===== */\n"
    ".typing{\n"
    "  display:flex;gap:6px;align-items:center;padding:10px 16px;\n"
    "  background:#181818;border-radius:18px;border-bottom-left-radius:4px;max-width:72%\n"
    "}\n"
    ".typing .text{font-size:12px;color:#666}\n"
    ".typing .dots{display:flex;gap:3px;align-items:center}\n"
    ".typing .dots span{\n"
    "  width:5px;height:5px;border-radius:50%;background:#555;\n"
    "  animation:typing 1.4s ease-in-out infinite\n"
    "}\n"
    ".typing .dots span:nth-child(2){animation-delay:.2s}\n"
    ".typing .dots span:nth-child(3){animation-delay:.4s}\n"
    "@keyframes typing{\n"
    "  0%,60%,100%{opacity:.3;transform:translateY(0)}\n"
    "  30%{opacity:1;transform:translateY(-4px)}\n"
    "}\n"
    "\n"
    "/* ===== 9. 输入栏 — 文本输入 + 发送按钮 ===== */\n"
    "#input-bar{\n"
    "  padding:0 16px 14px;flex-shrink:0;display:flex;flex-direction:column;align-items:center\n"
    "}\n"
    "#input-wrap{\n"
    "  max-width:700px;width:100%;position:relative\n"
    "}\n"
    "\n"
    "/* 胶囊形输入框, 支持 auto-resize */\n"
    "#msg-input{\n"
    "  width:100%;background:#1a1a1a;border:1px solid #2a2a2a;\n"
    "  border-radius:28px;color:#e0e0e0;padding:12px 50px 12px 18px;\n"
    "  font-size:14px;outline:none;font-family:inherit;\n"
    "  min-height:44px;max-height:200px;resize:none;overflow:hidden;line-height:1.5;transition:border .2s\n"
    "}\n"
    "#msg-input:focus{border-color:#3a3a3a}\n"
    "#msg-input::placeholder{color:#555}\n"
    "\n"
    "/* 发送按钮 — 蓝底白箭头, 绝对定位在输入框右侧 */\n"
    "/* (z-index:1) 防止 textarea 层叠导致 onclick 不触发 */\n"
    "#send-btn{\n"
    "  position:absolute;right:5px;top:50%;transform:translateY(-50%);\n"
    "  width:30px;height:30px;border-radius:50%;border:none;\n"
    "  background:#4a9eff;color:#fff;cursor:pointer;z-index:1;\n"
    "  display:flex;align-items:center;justify-content:center;\n"
    "  transition:.2s\n"
    "}\n"
    "#send-btn:hover{background:#3b82f6}\n"
    "#send-btn svg{width:16px;height:16px;fill:currentColor}\n"
    "\n"
    "/* 模型名称提示 — 输入框左下方灰字 */\n"
    "#model-hint{\n"
    "  max-width:700px;width:100%;font-size:11px;color:#444;padding:4px 6px 0;\n"
    "  text-align:left;line-height:1\n"
    "}\n"
    "\n"
    "/* ===== 10. 空状态 ↔ 聊天模式切换 ===== */\n"
    "/* chatting 类由 JS 在首次发送消息后添加 */\n"
    "#main.chatting #empty-state{display:none}\n"
    "#main.chatting #messages{display:block}\n"
    "#main:not(.chatting) #empty-state{display:flex}\n"
    "#main:not(.chatting) #messages{display:none}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<!-- ===== 顶栏 ===== -->\n"
    "<!-- 左侧: AiPiClaw 品牌名 / 右侧: 新建对话 + WiFi 图标 + 状态灯 -->\n"
    "<div id=\"topbar\">\n"
    "  <div id=\"brand\"><span>AiPi</span>Claw</div>\n"
    "  <div id=\"topbar-right\">\n"
    "    <!-- 新建对话按钮: 清空聊天记录, 回到空状态 -->\n"
    "    <button class=\"tb-btn\" onclick=\"newChat()\" title=\"新建对话\">+</button>\n"
    "    <a href=\"http://192.168.4.1/\" style=\"display:inline-flex;align-items:center;justify-content:center;width:30px;height:30px;color:#555;text-decoration:none;font-size:16px;transition:.2s\" title=\"返回配置\">⚙</a>\n"
    "    <!-- WiFi SVG 图标: 设备连接后表示信号状态 -->\n"
    "    <svg id=\"wifi-icon\" viewBox=\"0 0 24 24\"><path d=\"M1 9l2 2c4.97-4.97 13.03-4.97 18 0l2-2C16.93 2.93 7.08 2.93 1 9zm8 8l3 3 3-3c-1.65-1.66-4.34-1.66-6 0zm-4-4l2 2c2.76-2.76 7.24-2.76 10 0l2-2C15.14 9.14 8.87 9.14 5 13z\"/></svg>\n"
    "    <!-- 连接状态指示灯: 绿=已连接 / 黄=连接中 / 红=已断开 -->\n"
    "    <div id=\"status\">\n"
    "      <span class=\"dot yellow\" id=\"status-dot\"></span>\n"
    "      <span id=\"status-label\" class=\"yellow\">连接中</span>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<!-- ===== 聊天主区域 ===== -->\n"
    "<div id=\"main\">\n"
    "  <!-- 消息滚动容器: 自动从底部展开, 新消息追加到 #messages -->\n"
    "  <div id=\"chat-area\">\n"
    "    <!-- 空状态: 首次打开时显示, 发送消息后隐藏 -->\n"
    "    <div id=\"empty-state\">\n"
    "      <h1>今天有什么计划？</h1>\n"
    "      <div class=\"sub\">试试下面这些示例</div>\n"
    "      <!-- 推荐问题卡片: 点击自动填入并发送 -->\n"
    "      <div class=\"suggestions\">\n"
    "        <div class=\"card\" onclick=\"quickSend('打开GPIO17，点亮LED')\">\n"
    "          <span class=\"icon\">💡</span> 打开GPIO17，点亮LED\n"
    "        </div>\n"
    "        <div class=\"card\" onclick=\"quickSend('开关GPT's thoughts')\">\n"
    "          <span class=\"icon\">🔧</span> 开关GPT's thoughts\n"
    "        </div>\n"
    "        <div class=\"card\" onclick=\"quickSend('你好，你是谁？')\">\n"
    "          <span class=\"icon\">👋</span> 你好，你是谁？\n"
    "        </div>\n"
    "        <div class=\"card\" onclick=\"quickSend('Read sensor data')\">\n"
    "          <span class=\"icon\">📊</span> Read sensor data\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <!-- 消息列表: 动态由 JS 渲染 -->\n"
    "    <div id=\"messages\"></div>\n"
    "  </div>\n"
    "\n"
    "  <!-- 滚动到底部按钮 -->\n"
    "  <button id=\"scroll-btn\" onclick=\"scrollToBottom()\" title=\"滚动到底部\">↓</button>\n"
    "</div>\n"
    "\n"
    "<!-- ===== 输入栏 ===== -->\n"
    "<div id=\"input-bar\">\n"
    "  <div id=\"input-wrap\">\n"
    "    <textarea id=\"msg-input\" placeholder=\"给 AiPiClaw 发送消息...\" rows=\"1\" maxlength=\"4096\"></textarea>\n"
    "    <button id=\"send-btn\" onclick=\"sendMessage()\" title=\"发送\">\n"
    "      <svg viewBox=\"0 0 24 24\"><path d=\"M2.01 21L23 12 2.01 3 2 10l15 2-15 2z\"/></svg>\n"
    "    </button>\n"
    "  </div>\n"
    "  <div id=\"model-hint\"></div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "/* ================================================================\n"
    "   AiPiClaw Web Chat — 聊天界面 JS 逻辑\n"
    "   ================================================================\n"
    "   依赖: 无\n"
    "   协议: 纯文本 WebSocket 帧 (ws://{hostname}:18789)\n"
    "   性能: requestAnimationFrame + 文档片段批量渲染\n"
    "   Self-connect: IIFE 自动连接, 不依赖任何外部状态\n"
    "   ================================================================ */\n"
    "\n"
    "// ---- 1. 配置常量 ----\n"
    "var WS_PORT = 18789;\n"
    "var RECONN_DELAY = 3000;     // 初始重连间隔 (ms)\n"
    "var MAX_RECONN_DELAY = 30000; // 最长重连间隔 (ms)\n"
    "\n"
    "/**\n"
    " * localStorage key: AI 配置键名\n"
    " * LLM 配置:  localStorage key=\"mimi_web_config\", 存储 provider/model/apikey\n"
    " */\n"
    "var CFG_KEY = 'mimi_web_config';\n"
    "\n"
    "// ---- 2. 全局状态 ----\n"
    "var ws = null;             // WebSocket 实例\n"
    "var reconnCount = 0;       // 连续重连次数\n"
    "var reconnTimer = null;    // 重连计时器\n"
    "var pendingMsg = null;     // 正在发送但尚未收到回复的消息\n"
    "var lastAskId = 0;         // 已显示的消息序号, 用于去重\n"
    "var isAtBottom = true;     // 是否在滚动底部\n"
    "\n"
    "// ---- 3. DOM 缓存 ----\n"
    "var el = {};\n"
    "['chat-area','empty-state','messages','msg-input','send-btn',\n"
    " 'status','status-dot','status-label','model-hint','main'].forEach(function(id){\n"
    "  el[id] = document.getElementById(id);\n"
    "});\n"
    "\n"
    "// ---- 4. WebSocket 连接管理 ----\n"
    "/**\n"
    " * 建立 WebSocket 连接到 BL618 LLM 代理\n"
    " * 自动尝试连接当前页面的主机名\n"
    " */\n"
    "function connect(){\n"
    "  // 清理旧连接\n"
    "  if(ws){\n"
    "    try{ws.onclose=null;ws.onerror=null;ws.close();}catch(e){}\n"
    "    ws=null;\n"
    "  }\n"
    "\n"
    "  var host = location.hostname || '192.168.4.1';\n"
    "  var url = 'ws://' + host + ':' + WS_PORT;\n"
    "\n"
    "  try {\n"
    "    ws = new WebSocket(url);\n"
    "  } catch(e) {\n"
    "    setStatus('red','断开');\n"
    "    scheduleReconnect();\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  ws.onopen = function(){\n"
    "    reconnCount=0;\n"
    "    setStatus('green','已连接');\n"
    "    el['send-btn'].disabled=false;\n"
    "\n"
    "    // 若之前有未发送的待发消息, 连线后立即发送\n"
    "    if(pendingMsg){\n"
    "      var msg=pendingMsg;\n"
    "      pendingMsg=null;\n"
    "      doSend(msg);\n"
    "    }\n"
    "  };\n"
    "\n"
    "  ws.onclose = function(){\n"
    "    setStatus('red','断开');\n"
    "    el['send-btn'].disabled=true;\n"
    "    scheduleReconnect();\n"
    "  };\n"
    "\n"
    "  ws.onerror = function(){\n"
    "    // onclose 会随后触发, 不重复处理\n"
    "  };\n"
    "\n"
    "  ws.onmessage = function(e){\n"
    "    // 收到服务器消息\n"
    "    var text = e.data || '';\n"
    "    if(!text || typeof text !== 'string') return;\n"
    "\n"
    "    // 系统消息: 以 / 开头 (如 /clean /thinking /ping)\n"
    "    if(text.charAt(0) === '/'){\n"
    "      handleSysMsg(text);\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    // 错误/告警: LLM 返回特定错误前缀\n"
    "    var lower = text.toLowerCase();\n"
    "    if(\n"
    "      lower.includes('错误')||lower.includes('error')||\n"
    "      lower.includes('密钥')||lower.includes('key 缺失')||lower.includes('not configured')||\n"
    "      lower.indexOf('失败')>0\n"
    "    ){\n"
    "      addError('⚠️ LLM 返回错误: ' + text);\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    // 正常 AI 回复: 追加到聊天界面\n"
    "    addMessage(text, 'ai');\n"
    "  };\n"
    "}\n"
    "\n"
    "/**\n"
    " * 处理系统指令消息 (以 / 开头)\n"
    " * /clean   → 清空聊天记录\n"
    " * /thinking → (可选) AI 思考过程\n"
    " */\n"
    "function handleSysMsg(msg){\n"
    "  if(msg === '/clean' || msg === '/clear'){\n"
    "    el['messages'].innerHTML='';\n"
    "    return;\n"
    "  }\n"
    "  // 其他 / 消息忽略\n"
    "}\n"
    "\n"
    "/**\n"
    " * 安排重连: 指数退避\n"
    " */\n"
    "function scheduleReconnect(){\n"
    "  if(reconnTimer) return;\n"
    "  reconnCount++;\n"
    "  var delay = Math.min(\n"
    "    RECONN_DELAY * Math.pow(1.5, reconnCount-1),\n"
    "    MAX_RECONN_DELAY\n"
    "  );\n"
    "  // 添加随机抖动, 避免多设备同时重连\n"
    "  delay += Math.random() * 1000;\n"
    "  reconnTimer = setTimeout(function(){\n"
    "    reconnTimer=null;\n"
    "    connect();\n"
    "  }, delay);\n"
    "}\n"
    "\n"
    "/**\n"
    " * @返回 boolean 是否已连接\n"
    " */\n"
    "function isConnected(){\n"
    "  return ws && ws.readyState === WebSocket.OPEN;\n"
    "}\n"
    "\n"
    "/**\n"
    " * 设置连接状态指示器\n"
    " * @param {string} color green/red/yellow\n"
    " * @param {string} label\n"
    " */\n"
    "function setStatus(color, label){\n"
    "  el['status-dot'].className='dot '+color;\n"
    "  el['status-label'].className=color;\n"
    "  el['status-label'].textContent=label;\n"
    "}\n"
    "\n"
    "// ---- 5. 消息发送 ----\n"
    "/**\n"
    " * 发送文本到 WebSocket\n"
    " */\n"
    "function doSend(text){\n"
    "  if(!text || typeof text !== 'string') return;\n"
    "  try{\n"
    "    ws.send(text);\n"
    "  }catch(e){\n"
    "    pendingMsg=text;\n"
    "    setStatus('red','断开');\n"
    "    scheduleReconnect();\n"
    "  }\n"
    "}\n"
    "\n"
    "/**\n"
    " * 发送聊天消息 (UI 触发)\n"
    " * 从输入框读取文本, 清空输入框, 显示用户气泡, 发送到 WS\n"
    " */\n"
    "function sendMessage(){\n"
    "  if(!isConnected()){\n"
    "    addError('⚠️ 未连接到设备');\n"
    "    return;\n"
    "  }\n"
    "  var text = el['msg-input'].value.trim();\n"
    "  if(!text) return;\n"
    "\n"
    "  // 清空输入框\n"
    "  el['msg-input'].value='';\n"
    "  // 重置输入框高度\n"
    "  el['msg-input'].style.height='auto';\n"
    "\n"
    "  // 切换为空状态 → 聊天模式\n"
    "  el['main'].classList.add('chatting');\n"
    "\n"
    "  // 添加延迟发送提示(如果 3 秒未返回)\n"
    "  addMessage(text, 'user');\n"
    "  // 清除请求超时计时器 (收到回复说明 LLM 返回了)\n"
    "  doSend(text);\n"
    "}\n"
    "\n"
    "/**\n"
    " * 快捷发送: 点击推荐问题卡片\n"
    " * @param {string} text 要发送的文本\n"
    " */\n"
    "function quickSend(text){\n"
    "  if(!text) return;\n"
    "  el['msg-input'].value=text;\n"
    "  sendMessage();\n"
    "}\n"
    "\n"
    "/**\n"
    " * 新建对话: 清空历史, 回到空状态\n"
    " */\n"
    "function newChat(){\n"
    "  el['messages'].innerHTML='';\n"
    "  el['main'].classList.remove('chatting');\n"
    "  // 隐藏滚动按钮\n"
    "  el['scroll-btn'] && el['scroll-btn'].classList.remove('show');\n"
    "  el['chat-area'].scrollTop=0;\n"
    "}\n"
    "\n"
    "// ---- 6. 消息渲染 ----\n"
    "/**\n"
    " * 追加一条消息到聊天界面\n"
    " * @param {string} text  消息文本 (支持 Markdown)\n"
    " * @param {string} role  'user' | 'ai' | 'system' | 'error'\n"
    " */\n"
    "function addMessage(text, role){\n"
    "  role = role || 'ai';\n"
    "\n"
    "  // 清除 \"思考中...\" 占位\n"
    "  removeTyping();\n"
    "\n"
    "  var wrap = document.createElement('div');\n"
    "  wrap.className = 'msg ' + role;\n"
    "\n"
    "  var bubble = document.createElement('div');\n"
    "  bubble.className = 'bubble';\n"
    "\n"
    "  // 用户消息: 简单转义; AI 消息: Markdown 渲染\n"
    "  if(role === 'user'){\n"
    "    bubble.textContent = text;\n"
    "  } else if(role === 'ai'){\n"
    "    bubble.innerHTML = markdownToHtml(text);\n"
    "  } else {\n"
    "    bubble.textContent = text;\n"
    "  }\n"
    "\n"
    "  wrap.appendChild(bubble);\n"
    "  el['messages'].appendChild(wrap);\n"
    "  scheduleScrollCheck();\n"
    "}\n"
    "\n"
    "/**\n"
    " * 追加一条错误消息\n"
    " * @param {string} text 错误文本\n"
    " */\n"
    "function addError(text){\n"
    "  removeTyping();\n"
    "  var wrap = document.createElement('div');\n"
    "  wrap.className = 'msg error';\n"
    "  var bubble = document.createElement('div');\n"
    "  bubble.className = 'bubble';\n"
    "  bubble.textContent = text;\n"
    "  wrap.appendChild(bubble);\n"
    "  el['messages'].appendChild(wrap);\n"
    "  scheduleScrollCheck();\n"
    "}\n"
    "\n"
    "/**\n"
    " * 显示 \"思考中...\" 打字动画\n"
    " */\n"
    "function showTyping(){\n"
    "  removeTyping();\n"
    "  var wrap = document.createElement('div');\n"
    "  wrap.className = 'msg ai';\n"
    "  wrap.id = 'typing-wrap';\n"
    "  wrap.innerHTML =\n"
    "    '<div class=\"typing\">' +\n"
    "      '<div class=\"text\">思考中</div>' +\n"
    "      '<div class=\"dots\">' +\n"
    "        '<span></span><span></span><span></span>' +\n"
    "      '</div>' +\n"
    "    '</div>';\n"
    "  el['messages'].appendChild(wrap);\n"
    "  scheduleScrollCheck();\n"
    "}\n"
    "\n"
    "/**\n"
    " * 移除 \"思考中...\" 占位\n"
    " */\n"
    "function removeTyping(){\n"
    "  var tw = document.getElementById('typing-wrap');\n"
    "  if(tw) tw.remove();\n"
    "}\n"
    "\n"
    "// ---- 7. Markdown 渲染 ----\n"
    "/**\n"
    " * 简易 Markdown 转 HTML (覆盖常用格式)\n"
    " * 支持: 代码块 ```, 行内 `code`, **粗体**, *斜体*,\n"
    " *       无序列表 -, 有序列表 1., [链接](url)\n"
    " * @param {string} text 原始 Markdown 文本\n"
    " * @返回 {string} 渲染后的 HTML\n"
    " */\n"
    "function markdownToHtml(text){\n"
    "  if(!text) return '';\n"
    "  var html = text;\n"
    "\n"
    "  // 转义 HTML 标签 (确保安全)\n"
    "  html = html\n"
    "    .replace(/&/g, '&amp;')\n"
    "    .replace(/</g, '&lt;')\n"
    "    .replace(/>/g, '&gt;');\n"
    "\n"
    "  // 代码块: ```...``` → <pre><code>...</code></pre>\n"
    "  html = html.replace(/```([\\s\\S]*?)```/g, function(m, code){\n"
    "    return '<pre><code>' + code.trim() + '</code></pre>';\n"
    "  });\n"
    "\n"
    "  // 行内代码: `code` → <code>code</code>\n"
    "  html = html.replace(/`([^`]+)`/g, '<code>$1</code>');\n"
    "\n"
    "  // 加粗: **text** → <strong>text</strong>\n"
    "  html = html.replace(/\\*\\*(.+?)\\*\\*/g, '<strong>$1</strong>');\n"
    "\n"
    "  // 斜体: *text* → <em>text</em>\n"
    "  html = html.replace(/\\*(.+?)\\*/g, '<em>$1</em>');\n"
    "\n"
    "  // 链接: [text](url) → <a href=\"url\">text</a>\n"
    "  html = html.replace(/\\[([^\\]]+)\\]\\(([^)]+)\\)/g, '<a href=\"$2\">$1</a>');\n"
    "\n"
    "  // 将文本按行分割处理列表\n"
    "  var lines = html.split('\n"
    "');\n"
    "  var result = [];\n"
    "  var inUl = false;\n"
    "  var inOl = false;\n"
    "\n"
    "  for(var i=0; i<lines.length; i++){\n"
    "    var line = lines[i];\n"
    "\n"
    "    // 跳过空行时关闭列表\n"
    "    if(!line.trim()){\n"
    "      if(inUl){ result.push('</ul>'); inUl=false; }\n"
    "      if(inOl){ result.push('</ol>'); inOl=false; }\n"
    "      result.push('<p></p>');  // 空段落作为分段\n"
    "      continue;\n"
    "    }\n"
    "\n"
    "    // 无序列表: -, *, +\n"
    "    if(/^[\\s]*[-*+][\\s]+/.test(line)){\n"
    "      if(!inUl){ result.push('<ul>'); inUl=true; }\n"
    "      if(inOl){ result.push('</ol>'); inOl=false; }\n"
    "      result.push('<li>' + line.replace(/^[\\s]*[-*+][\\s]+/, '') + '</li>');\n"
    "      continue;\n"
    "    }\n"
    "\n"
    "    // 有序列表: 1., 2. 等\n"
    "    if(/^[\\s]*\\d+\\.[\\s]+/.test(line)){\n"
    "      if(!inOl){ result.push('<ol>'); inOl=true; }\n"
    "      if(inUl){ result.push('</ul>'); inUl=false; }\n"
    "      result.push('<li>' + line.replace(/^[\\s]*\\d+\\.[\\s]+/, '') + '</li>');\n"
    "      continue;\n"
    "    }\n"
    "\n"
    "    // 普通段落\n"
    "    if(inUl){ result.push('</ul>'); inUl=false; }\n"
    "    if(inOl){ result.push('</ol>'); inOl=false; }\n"
    "    result.push('<p>' + line.trim() + '</p>');\n"
    "  }\n"
    "\n"
    "  // 关闭未闭合的列表\n"
    "  if(inUl) result.push('</ul>');\n"
    "  if(inOl) result.push('</ol>');\n"
    "\n"
    "  return result.join('\n"
    "');\n"
    "}\n"
    "\n"
    "// ---- 8. 滚动管理 ----\n"
    "/**\n"
    " * @返回 {boolean} 是否在底部 (误差 100px)\n"
    " */\n"
    "function isNearBottom(){\n"
    "  var area = el['chat-area'];\n"
    "  return area.scrollHeight - area.scrollTop - area.clientHeight < 100;\n"
    "}\n"
    "\n"
    "/**\n"
    " * 滚动到底部 (平滑)\n"
    " */\n"
    "function scrollToBottom(){\n"
    "  el['chat-area'].scrollTop = el['chat-area'].scrollHeight;\n"
    "}\n"
    "\n"
    "/**\n"
    " * 监控滚动位置, 控制 \"滚动到底部\" 按钮显隐\n"
    " */\n"
    "el['chat-area'].addEventListener('scroll', function(){\n"
    "  isAtBottom = isNearBottom();\n"
    "  var btn = document.getElementById('scroll-btn');\n"
    "  if(btn){\n"
    "    if(isAtBottom){\n"
    "      btn.classList.remove('show');\n"
    "    } else {\n"
    "      btn.classList.add('show');\n"
    "    }\n"
    "  }\n"
    "});\n"
    "\n"
    "/**\n"
    " * 使用 requestAnimationFrame 调度滚动检查\n"
    " * 分批渲染后统一复位滚动位置\n"
    " */\n"
    "var _scrollScheduled = false;\n"
    "function scheduleScrollCheck(){\n"
    "  if(_scrollScheduled) return;\n"
    "  _scrollScheduled = true;\n"
    "  requestAnimationFrame(function(){\n"
    "    _scrollScheduled = false;\n"
    "    if(isNearBottom()){\n"
    "      el['chat-area'].scrollTop = el['chat-area'].scrollHeight;\n"
    "    }\n"
    "  });\n"
    "}\n"
    "\n"
    "// ---- 9. 输入框自动伸缩 ----\n"
    "el['msg-input'].addEventListener('input', function(){\n"
    "  this.style.height = 'auto';\n"
    "  this.style.height = this.scrollHeight + 'px';\n"
    "});\n"
    "\n"
    "// ---- 10. 键盘快捷键 ----\n"
    "// Enter 发送, Shift+Enter 换行\n"
    "el['msg-input'].addEventListener('keydown', function(e){\n"
    "  if(e.key === 'Enter' && !e.shiftKey){\n"
    "    e.preventDefault();\n"
    "    sendMessage();\n"
    "  }\n"
    "});\n"
    "\n"
    "// ---- 11. 模型提示 ----\n"
    "/**\n"
    " * 从 localStorage 读取 LLM 配置并显示模型名\n"
    " */\n"
    "function loadConfig(){\n"
    "  try{\n"
    "    var raw = localStorage.getItem(CFG_KEY);\n"
    "    if(raw){\n"
    "      var cfg = JSON.parse(raw);\n"
    "      if(cfg && cfg.model){\n"
    "        el['model-hint'].textContent = cfg.model;\n"
    "      } else {\n"
    "        el['model-hint'].textContent = '';\n"
    "      }\n"
    "    }\n"
    "  } catch(e){}\n"
    "}\n"
    "\n"
    "// ---- 12. 滚动按钮绑定 ----\n"
    "var scrollBtn = document.getElementById('scroll-btn');\n"
    "if(scrollBtn){\n"
    "  scrollBtn.addEventListener('click', scrollToBottom);\n"
    "}\n"
    "\n"
    "// ---- 13. 自动连接 ----\n"
    "// 页面加载后自动 WebSocket 连接\n"
    "loadConfig();\n"
    "connect();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "";

#endif /* _WEB_UI_H_ */
