/**
 * @file web_ui.h
 * @brief Web UI HTML page - AiPiClaw AI Agent Web Chat Interface
 * @note  Auto-generated from web_ui.html. Contains HTML+CSS+JS with Chinese annotations.
 */

#ifndef WEB_UI_H
#define WEB_UI_H

static const char WEB_UI_HTML[] =
    "<!DOCTYPE html>\n"
    "<!--\n"
    "  =============================================================\n"
    "  AiPiClaw Web Chat — AiPiClaw AI Agent Web 聊天界面\n"
    "  =============================================================\n"
    "  用途: 通过 WebSocket 与 BL618 固件通信, 实现 AI 对话交互\n"
    "  连接: ws://{hostname}:18789 (自动连接)\n"
    "  协议: 纯文本帧, UTF-8 编码, 无 JSON 封装\n"
    "  依赖: 零外部依赖, 纯 HTML + CSS + JS\n"
    "  作者: 安信可科技 Ai-Thinker\n"
    "=============================================================\n"
    "-->\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
    "<title>AiPiClaw</title>\n"
    "<style>\n"
    "/* ===== 1. 全局重置 & 基础样式 ===== */\n"
    "/* 清除浏览器默认边距, 统一盒模型 */\n"
    "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    "html,body{height:100%;overflow:hidden}\n"
    "body{\n"
    "  font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",\"Noto Sans SC\",sans-serif;\n"
    "  background:#000;color:#fff;display:flex;flex-direction:column\n"
    "}\n"
    "\n"
    "/* ===== 2. 顶栏 — 品牌名 / 操作按钮 / 连接状态 ===== */\n"
    "#topbar{\n"
    "  display:flex;align-items:center;justify-content:space-between;\n"
    "  padding:10px 20px;flex-shrink:0;min-height:50px;position:relative\n"
    "}\n"
    "#brand{font-size:16px;font-weight:600;color:#eee;letter-spacing:.3px}\n"
    "#brand span{color:#4a9eff} /* AiPi 蓝色高亮 */\n"
    "\n"
    "/* 右上角功能区 */\n"
    "#topbar-right{display:flex;align-items:center;gap:10px}\n"
    "\n"
    "/* 状态指示灯 — 12px 圆点 + 发光效果 */\n"
    ".dot{width:12px;height:12px;border-radius:50%;display:inline-block;flex-shrink:0}\n"
    ".dot.green{background:#2ecc71;box-shadow:0 0 8px rgba(46,204,113,.5)}\n"
    ".dot.red{background:#e74c3c;box-shadow:0 0 8px rgba(231,76,60,.5)}\n"
    ".dot.yellow{background:#f39c12;box-shadow:0 0 8px rgba(243,156,18,.5)}\n"
    "\n"
    "/* 状态文字标签 — 跟随状态变色 */\n"
    "#status-label{font-size:11px;font-weight:500}\n"
    "#status-label.green{color:#2ecc71}\n"
    "#status-label.red{color:#e74c3c}\n"
    "#status-label.yellow{color:#f39c12}\n"
    "\n"
    "/* 通用小型按钮 */\n"
    ".tb-btn{\n"
    "  background:transparent;border:1px solid #333;border-radius:6px;\n"
    "  color:#555;padding:3px 8px;font-size:12px;cursor:pointer;transition:.2s;\n"
    "  line-height:1.2\n"
    "}\n"
    ".tb-btn:hover{background:#111;color:#aaa;border-color:#444}\n"
    "\n"
    "/* WiFi 信号图标 */\n"
    "#wifi-icon{fill:#555;width:16px;height:16px;vertical-align:middle}\n"
    "\n"
    "/* ===== 3. 聊天主区域 — 消息滚动容器 ===== */\n"
    "#main{\n"
    "  flex:1;display:flex;flex-direction:column;position:relative;\n"
    "  overflow:hidden;min-height:0\n"
    "}\n"
    "#chat-area{\n"
    "  flex:1;overflow-y:auto;padding:0 0 16px;\n"
    "  display:flex;flex-direction:column;justify-content:flex-end\n"
    "}\n"
    "/* 极简滚动条, 适应深色主题 */\n"
    "#chat-area::-webkit-scrollbar{width:4px}\n"
    "#chat-area::-webkit-scrollbar-track{background:transparent}\n"
    "#chat-area::-webkit-scrollbar-thumb{background:#222;border-radius:2px}\n"
    "\n"
    "/* ===== 4. 悬浮\"滚动到底\"按钮 ===== */\n"
    "/* 用户向上滚动时显示, 点击回到最新消息 */\n"
    "#scroll-btn{\n"
    "  position:absolute;bottom:80px;right:20px;\n"
    "  background:#1a1a1a;border:1px solid #333;border-radius:50%;\n"
    "  width:36px;height:36px;color:#888;cursor:pointer;z-index:10;\n"
    "  display:none;align-items:center;justify-content:center;\n"
    "  transition:opacity .3s;box-shadow:0 2px 12px rgba(0,0,0,.6)\n"
    "}\n"
    "#scroll-btn.show{display:flex}\n"
    "#scroll-btn:hover{background:#222;color:#ccc}\n"
    "\n"
    "/* ===== 5. 空状态引导区 — 首次打开时显示 ===== */\n"
    "/* 包含标题 + 推荐问题卡片, 发送第一条消息后自动隐藏 */\n"
    "#empty-state{\n"
    "  display:flex;flex-direction:column;align-items:center;\n"
    "  justify-content:center;flex:1;padding:0 20px 40px\n"
    "}\n"
    "#empty-state h1{font-size:26px;font-weight:500;color:#e0e0e0;margin-bottom:6px}\n"
    "#empty-state .sub{font-size:13px;color:#555;margin-bottom:24px}\n"
    ".suggestions{display:flex;flex-direction:column;gap:8px;width:100%;max-width:360px}\n"
    ".suggestions .card{\n"
    "  background:#111;border:1px solid #222;border-radius:12px;\n"
    "  padding:12px 16px;cursor:pointer;transition:.2s;\n"
    "  display:flex;align-items:center;gap:10px;font-size:13px;color:#999\n"
    "}\n"
    ".suggestions .card:hover{background:#1a1a1a;border-color:#333;color:#ccc}\n"
    ".suggestions .card .icon{font-size:18px;flex-shrink:0}\n"
    "\n"
    "/* ===== 6. 消息气泡 — 用户/AI/系统/错误四种样式 ===== */\n"
    "/* max-width:720px 居中容器, padding 提供左右留白 */\n"
    "#messages{width:100%;max-width:720px;margin:0 auto;padding:16px 20px 8px}\n"
    ".msg{display:flex;margin-bottom:14px}\n"
    ".msg.user{justify-content:flex-end}   /* 用户气泡靠右 */\n"
    ".msg.ai{justify-content:flex-start}   /* AI 气泡靠左 */\n"
    "\n"
    "/* 气泡通用样式 */\n"
    ".bubble{\n"
    "  max-width:72%;font-size:14px;line-height:1.6;word-break:break-word;\n"
    "  padding:10px 16px;border-radius:18px\n"
    "}\n"
    ".msg.user .bubble{\n"
    "  background:#2a2a2a;color:#e0e0e0;border-bottom-right-radius:4px  /* 用户: 右下角收口 */\n"
    "}\n"
    ".msg.ai .bubble{\n"
    "  background:#181818;color:#ccc;border-bottom-left-radius:4px    /* AI: 左下角收口 */\n"
    "}\n"
    ".msg.system{justify-content:center;margin-bottom:6px}\n"
    ".msg.system .bubble{\n"
    "  background:transparent;color:#444;font-size:11px;padding:4px 0\n"
    "}\n"
    "/* LLM 错误消息 — 红色边框提醒 */\n"
    ".msg.error{justify-content:center;margin-bottom:6px}\n"
    ".msg.error .bubble{\n"
    "  background:rgba(231,76,60,.1);border:1px solid rgba(231,76,60,.3);\n"
    "  color:#e74c3c;font-size:12px;padding:8px 14px;border-radius:12px\n"
    "}\n"
    ".bubble .time{\n"
    "  display:block;font-size:10px;margin-top:4px\n"
    "}\n"
    ".msg.user .bubble .time{color:rgba(255,255,255,.15);text-align:right}\n"
    ".msg.ai .bubble .time{color:#333}\n"
    "\n"
    "/* ===== 7. Markdown 渲染 — AI 回复中的富文本 ===== */\n"
    ".bubble em{font-style:italic}\n"
    ".bubble strong{font-weight:600;color:#e8e8e8}\n"
    ".bubble code{\n"
    "  background:rgba(255,255,255,.06);color:#e6c07b;padding:1px 5px;\n"
    "  border-radius:4px;font-size:13px;font-family:\"Consolas\",\"Courier New\",monospace\n"
    "}\n"
    ".bubble pre{\n"
    "  background:#0d0d0d;border:1px solid #222;border-radius:8px;\n"
    "  padding:10px 14px;margin:6px 0;overflow-x:auto;font-size:13px\n"
    "}\n"
    ".bubble pre code{background:none;padding:0;border-radius:0}\n"
    ".bubble a{color:#4a9eff;text-decoration:none}\n"
    ".bubble a:hover{text-decoration:underline}\n"
    ".bubble ul,.bubble ol{padding-left:20px;margin:4px 0}\n"
    ".bubble li{margin:2px 0}\n"
    "\n"
    "/* ===== 8. 打字动画 — AI 思考中三点弹跳 + 状态文案 ===== */\n"
    ".typing{\n"
    "  display:flex;gap:6px;align-items:center;padding:10px 16px;\n"
    "  background:#181818;border-radius:18px;border-bottom-left-radius:4px;max-width:72%\n"
    "}\n"
    ".typing .text{font-size:12px;color:#666}\n"
    ".typing .dots{display:flex;gap:3px;align-items:center}\n"
    ".typing .dots span{\n"
    "  width:5px;height:5px;border-radius:50%;background:#555;\n"
    "  animation:typing 1.4s ease-in-out infinite\n"
    "}\n"
    ".typing .dots span:nth-child(2){animation-delay:.2s}\n"
    ".typing .dots span:nth-child(3){animation-delay:.4s}\n"
    "@keyframes typing{\n"
    "  0%,60%,100%{opacity:.3;transform:translateY(0)}\n"
    "  30%{opacity:1;transform:translateY(-4px)}\n"
    "}\n"
    "\n"
    "/* ===== 9. 输入栏 — 文本输入 + 发送按钮 ===== */\n"
    "#input-bar{\n"
    "  padding:0 16px 14px;flex-shrink:0;display:flex;flex-direction:column;align-items:center\n"
    "}\n"
    "#input-wrap{\n"
    "  max-width:700px;width:100%;position:relative\n"
    "}\n"
    "\n"
    "/* 胶囊形输入框, 支持 auto-resize */\n"
    "#msg-input{\n"
    "  width:100%;background:#1a1a1a;border:1px solid #2a2a2a;\n"
    "  border-radius:28px;color:#e0e0e0;padding:12px 50px 12px 18px;\n"
    "  font-size:14px;outline:none;font-family:inherit;\n"
    "  min-height:44px;max-height:200px;resize:none;overflow:hidden;line-height:1.5;transition:border .2s\n"
    "}\n"
    "#msg-input:focus{border-color:#3a3a3a}\n"
    "#msg-input::placeholder{color:#555}\n"
    "\n"
    "/* 发送按钮 — 蓝底白箭头, 绝对定位在输入框右侧 */\n"
    "/* (z-index:1) 防止 textarea 层叠导致 onclick 不触发 */\n"
    "#send-btn{\n"
    "  position:absolute;right:5px;top:50%;transform:translateY(-50%);\n"
    "  width:30px;height:30px;border-radius:50%;border:none;\n"
    "  background:#4a9eff;color:#fff;cursor:pointer;z-index:1;\n"
    "  display:flex;align-items:center;justify-content:center;\n"
    "  transition:.2s\n"
    "}\n"
    "#send-btn:hover{background:#3b82f6}\n"
    "#send-btn svg{width:16px;height:16px;fill:currentColor}\n"
    "\n"
    "/* 模型名称提示 — 输入框左下方灰字 */\n"
    "#model-hint{\n"
    "  max-width:700px;width:100%;font-size:11px;color:#444;padding:4px 6px 0;\n"
    "  text-align:left;line-height:1\n"
    "}\n"
    "\n"
    "/* ===== 10. 空状态 ↔ 聊天模式切换 ===== */\n"
    "/* chatting 类由 JS 在首次发送消息后添加 */\n"
    "#main.chatting #empty-state{display:none}\n"
    "#main.chatting #messages{display:block}\n"
    "#main:not(.chatting) #empty-state{display:flex}\n"
    "#main:not(.chatting) #messages{display:none}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<!-- ===== 顶栏 ===== -->\n"
    "<!-- 左侧: AiPiClaw 品牌名 / 右侧: 新建对话 + WiFi 图标 + 状态灯 -->\n"
    "<div id=\"topbar\">\n"
    "  <div id=\"brand\"><span>AiPi</span>Claw</div>\n"
    "  <div id=\"topbar-right\">\n"
    "    <!-- 新建对话按钮: 清空聊天记录, 回到空状态 -->\n"
    "    <button class=\"tb-btn\" onclick=\"newChat()\" title=\"新建对话\">+</button>\n"
    "    <!-- WiFi SVG 图标: 设备连接后表示信号状态 -->\n"
    "    <svg id=\"wifi-icon\" viewBox=\"0 0 24 24\"><path d=\"M1 9l2 2c4.97-4.97 13.03-4.97 18 0l2-2C16.93 2.93 7.08 2.93 1 9zm8 8l3 3 3-3c-1.65-1.66-4.34-1.66-6 0zm-4-4l2 2c2.76-2.76 7.24-2.76 10 0l2-2C15.14 9.14 8.87 9.14 5 13z\"/></svg>\n"
    "    <!-- 连接状态指示灯: 绿=已连接 / 黄=连接中 / 红=已断开 -->\n"
    "    <div id=\"status\">\n"
    "      <span class=\"dot yellow\" id=\"status-dot\"></span>\n"
    "      <span id=\"status-label\" class=\"yellow\">连接中</span>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<!-- ===== 聊天主区域 ===== -->\n"
    "<div id=\"main\">\n"
    "  <!-- 消息滚动容器: 自动从底部展开, 新消息追加到 #messages -->\n"
    "  <div id=\"chat-area\">\n"
    "    <!-- 空状态: 首次打开时显示, 发送消息后隐藏 -->\n"
    "    <div id=\"empty-state\">\n"
    "      <h1>今天有什么计划？</h1>\n"
    "      <div class=\"sub\">试试下面这些示例</div>\n"
    "      <!-- 推荐问题卡片: 点击自动填入并发送 -->\n"
    "      <div class=\"suggestions\">\n"
    "        <div class=\"card\" onclick=\"quickSend('打开GPIO17，点亮LED')\">\n"
    "          <span class=\"icon\">⚡</span>\n"
    "          <span>打开GPIO17，点亮LED</span>\n"
    "        </div>\n"
    "        <div class=\"card\" onclick=\"quickSend('今天深圳天气怎么样？')\">\n"
    "          <span class=\"icon\">🌤</span>\n"
    "          <span>查询今天天气</span>\n"
    "        </div>\n"
    "        <div class=\"card\" onclick=\"quickSend('设置5分钟后提醒我关灯')\">\n"
    "          <span class=\"icon\">⏰</span>\n"
    "          <span>设置5分钟提醒</span>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <!-- 消息容器: JS 动态插入 .msg 元素 -->\n"
    "    <div id=\"messages\"></div>\n"
    "  </div>\n"
    "  <!-- 悬浮滚动到底按钮: 非底部时出现 -->\n"
    "  <button id=\"scroll-btn\" onclick=\"scrollBottom()\">\n"
    "    <svg viewBox=\"0 0 24 24\" style=\"width:18px;height:18px;fill:currentColor\"><path d=\"M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6z\"/></svg>\n"
    "  </button>\n"
    "</div>\n"
    "\n"
    "<!-- ===== 输入栏 ===== -->\n"
    "<!-- 固定在底部, 包含文本输入框 + 发送按钮 + 模型名提示 -->\n"
    "<div id=\"input-bar\">\n"
    "  <div id=\"input-wrap\">\n"
    "    <!-- 胶囊输入框: auto-resize, Enter 发送, Shift+Enter 换行 -->\n"
    "    <textarea id=\"msg-input\" rows=\"1\" placeholder=\"有问题尽管问 · Enter 发送\"></textarea>\n"
    "    <!-- 发送按钮: 蓝底白箭头 -->\n"
    "    <button id=\"send-btn\" onclick=\"sendMessage()\">\n"
    "      <svg viewBox=\"0 0 24 24\"><path d=\"M2.01 21L23 12 2.01 3 2 10l15 2-15 2z\"/></svg>\n"
    "    </button>\n"
    "  </div>\n"
    "  <!-- 模型名称提示: 左下角灰色小字, 通过 updateModelHint() 更新 -->\n"
    "  <div id=\"model-hint\"></div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "/**\n"
    " * ==================================================\n"
    " * AiPiClaw Web Chat — JavaScript 逻辑\n"
    " * ==================================================\n"
    " *\n"
    " * == WebSocket 通信协议 ==\n"
    " * 连接地址: ws://{window.location.hostname}:18789\n"
    " * 消息格式: 纯文本帧, UTF-8 编码\n"
    " * 心跳机制:\n"
    " *   - 每 10s 发送文本帧 \"__ping__\"\n"
    " *   - 期望 8s 内收到回复 \"__pong__\", 否则主动断连重连\n"
    " * 数据流:\n"
    " *   [用户输入] → sendMessage() → ws.send(文本)\n"
    " *     → 固件接收 → agent_loop 处理 → LLM 调用\n"
    " *     → 结果经 outbound bus → axk_ws_server_send() → broadcast 到所有 WS 客户端\n"
    " *   [ws.onmessage] → hideTyping() → startTypewriter() 逐字输出\n"
    " *\n"
    " * == 重连策略 ==\n"
    " * 指数退避: 1s, 2s, 4s, 8s, 16s, 30s(上限), 无限重试\n"
    " * 首次连接超时: 30s\n"
    " * 触发条件: onclose / onerror / pong 超时 / 连接超时\n"
    " *\n"
    " * == 消息持久化 ==\n"
    " * 聊天记录: localStorage key=\"mimi_chat_msgs\", 上限 200 条\n"
    " * LLM 配置:  localStorage key=\"mimi_web_config\", 存储 provider/model/apikey\n"
    " *\n"
    " * == LLM 状态反馈 ==\n"
    " * - 发送消息后: 显示 \"AI思考中...\" + 三点弹跳动画\n"
    " * - 30s 无回复: 显示 \"⚠️ 请求超时，请重试\" (红色警告)\n"
    " * - API Key 缺失: 检测错误文案, 显示 \"❌ 请先设置API Key\"\n"
    " * - LLM 错误: 检测 error/fail 等关键词, 显示原文错误信息 (红色边框)\n"
    " * ==================================================\n"
    " */\n"
    "(function(){\n"
    "'use strict';\n"
    "\n"
    "// ========================== 状态变量 ==========================\n"
    "// @用途 保存 WebSocket 连接、计时器、配置的运行时状态\n"
    "let ws=null,connected=false,sendPing=null,pongTimer=null;\n"
    "let reconnTimer=null,reconnCount=0;\n"
    "let cfgProvider='',cfgModel='',cfgApiKey=false;\n"
    "let msgCount=0,hasSent=false,typingEl=null,typewriterActive=false;\n"
    "let atBottom=true;\n"
    "let msgTimer=null; // @用途 LLM 请求超时计时器 (30s)\n"
    "\n"
    "/**\n"
    " * @用途 更新输入框左下方的模型名称提示\n"
    " * @说明 从 cfgModel 读取, 写入 #model-hint 元素\n"
    " *        无模型配置时留空不显示\n"
    " */\n"
    "function updateModelHint(){\n"
    "  const el=$('model-hint');\n"
    "  if(el)el.textContent=cfgModel||'';\n"
    "}\n"
    "\n"
    "// ========================== DOM 快捷引用 ==========================\n"
    "const $=id=>document.getElementById(id);\n"
    "const msgInput=$('msg-input'),sendBtn=$('send-btn'),msgArea=$('messages');\n"
    "const statusDot=$('status-dot');\n"
    "const mainEl=$('main');\n"
    "const chatArea=$('chat-area'),scrollBtn=$('scroll-btn');\n"
    "\n"
    "// ========================== 滚动控制 ==========================\n"
    "/**\n"
    " * @用途 滚动到聊天区最底部\n"
    " * @说明 同时检查当前是否在底部, 用于控制悬浮按钮显示\n"
    " */\n"
    "function scrollBottom(){\n"
    "  chatArea.scrollTop=chatArea.scrollHeight;checkScroll();\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 判断用户是否在聊天区底部 (误差 60px)\n"
    " * @返回 boolean\n"
    " */\n"
    "function isAtBottom(){\n"
    "  return chatArea.scrollHeight-chatArea.scrollTop-chatArea.clientHeight<60;\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 监听滚动事件, 非底部时显示悬浮按钮\n"
    " * @说明 绑定到 chat-area 的 scroll 事件\n"
    " */\n"
    "function checkScroll(){\n"
    "  atBottom=isAtBottom();\n"
    "  scrollBtn.classList.toggle('show',!atBottom&&msgCount>0);\n"
    "}\n"
    "chatArea.addEventListener('scroll',checkScroll);\n"
    "\n"
    "// ========================== 工具函数 ==========================\n"
    "function pad(n){return('0'+n).slice(-2)}\n"
    "function timeStr(){const d=new Date();return pad(d.getHours())+':'+pad(d.getMinutes());}\n"
    "\n"
    "// ========================== 连接管理 ==========================\n"
    "/**\n"
    " * @用途 更新连接状态指示灯\n"
    " * @参数 state {string} 'green' | 'yellow' | 'red'\n"
    " *        分别对应: 已连接 / 连接中 / 已断开\n"
    " * @说明 同时更新圆点颜色和文字标签\n"
    " */\n"
    "function setStatus(state){\n"
    "  statusDot.className='dot '+state;\n"
    "  const label=$('status-label');\n"
    "  if(label){label.className='status-label '+state;label.textContent=state==='green'?'已连接':state==='yellow'?'连接中':'已断开';}\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 建立 WebSocket 连接\n"
    " * @说明 连接 ws://{hostname}:18789, 30s 超时\n"
    " *        连接成功后: 刷新状态、发送暂存消息、启动心跳\n"
    " *        失败时: 指数退避重连\n"
    " *\n"
    " * == WebSocket 协议说明 ==\n"
    " * 1)  onopen: 连接建立, 清 pending 队列, 启动 10s 心跳\n"
    " * 2)  onmessage: 收到文本帧, 过滤 __ping__/__pong__, 其余作为 AI 回复\n"
    " * 3)  onclose: 连接断开, 清理计时器, 自动重连\n"
    " * 4)  onerror: 连接错误, 清理后重连\n"
    " */\n"
    "function connect(){\n"
    "  if(ws){ws.onclose=null;ws.close();ws=null;}\n"
    "  if(reconnTimer){clearTimeout(reconnTimer);reconnTimer=null;}\n"
    "  const host=window.location.hostname;\n"
    "  const url='ws://'+host+':18789';\n"
    "  setStatus('yellow');\n"
    "  ws=new WebSocket(url);\n"
    "  // 30s 连接超时: RST 后设备需要时间 boot + WiFi 初始化\n"
    "  let connTimeout=setTimeout(function(){\n"
    "    if(ws&&ws.readyState!==1){\n"
    "      ws.onclose=function(){};\n"
    "      ws.close();ws=null;\n"
    "      setStatus('red');\n"
    "      scheduleReconnect();\n"
    "    }\n"
    "  },30000);\n"
    "\n"
    "  // @用途 WebSocket 连接成功回调\n"
    "  // @说明 清 pending 队列, 启动 10s 心跳\n"
    "  ws.onopen=function(){\n"
    "    clearTimeout(connTimeout);\n"
    "    connected=true;reconnCount=0;\n"
    "    setStatus('green');\n"
    "    // 发送暂存的消息\n"
    "    while(pendingMsgs.length){\n"
    "      const m=pendingMsgs.shift();\n"
    "      try{ws.send(m);}catch(e){pendingMsgs.unshift(m);break;}\n"
    "    }\n"
    "    // 启动心跳: 每 10s 发 __ping__, 8s 内未收 __pong__ 则断连\n"
    "    if(sendPing)clearInterval(sendPing);\n"
    "    sendPing=setInterval(function(){\n"
    "      try{\n"
    "        if(ws.readyState!==1){clearInterval(sendPing);return;}\n"
    "        ws.send('__ping__');\n"
    "        if(pongTimer)clearTimeout(pongTimer);\n"
    "        pongTimer=setTimeout(function(){if(ws)ws.close();},8000);\n"
    "      }catch(e){clearInterval(sendPing);}\n"
    "    },10000);\n"
    "  };\n"
    "\n"
    "  // @用途 WebSocket 消息接收回调\n"
    "  // @参数 e {MessageEvent} 包含服务端发来的文本帧\n"
    "  // @说明 过滤心跳帧, 其余作为 AI 回复消息渲染\n"
    "  //        检测 LLM 错误/API Key 缺失等状态, 用不同样式展示\n"
    "  ws.onmessage=function(e){\n"
    "    if(typeof e.data!=='string'||!e.data.trim())return;\n"
    "    const t=e.data.trim();\n"
    "    // __pong__: 心跳响应, 清除 pong 超时\n"
    "    if(t.startsWith('__pong__')){if(pongTimer){clearTimeout(pongTimer);pongTimer=null;}return;}\n"
    "    // __ping__: 忽略自己发的 ping 回声\n"
    "    if(t.startsWith('__ping__'))return;\n"
    "    // 清除请求超时计时器 (收到回复说明 LLM 返回了)\n"
    "    if(msgTimer){clearTimeout(msgTimer);msgTimer=null;}\n"
    "    hideTyping();\n"
    "    if(typewriterActive)finishTypewriter();\n"
    "    // 检测 API Key 缺失\n"
    "    const lower=t.toLowerCase();\n"
    "    if(lower.includes('api key')||lower.includes('api_key')||lower.includes('apikey')||\n"
    "       lower.includes('密钥')||lower.includes('key 缺失')||lower.includes('not configured')||\n"
    "       lower.includes('auth')||lower.includes('401')||lower.includes('403')){\n"
    "      addError('❌ 请先设置API Key (使用 /key <API Key>)');\n"
    "      return;\n"
    "    }\n"
    "    // 检测 LLM 调用错误\n"
    "    if(lower.includes('error')||lower.includes('fail')||lower.includes('exception')||\n"
    "       lower.includes('timeout')||lower.includes('超时')||lower.includes('错误')||\n"
    "       lower.includes('sorry')||lower.includes('unavailable')||lower.includes('rate limit')){\n"
    "      addError('⚠️ LLM 返回错误: ' + t);\n"
    "      return;\n"
    "    }\n"
    "    // 正常 AI 回复\n"
    "    addMsg('ai',t);\n"
    "  };\n"
    "\n"
    "  // @用途 WebSocket 连接断开回调\n"
    "  // @说明 清理所有计时器, 重置连接状态, 自动重连\n"
    "  ws.onclose=function(){\n"
    "    clearTimeout(connTimeout);\n"
    "    connected=false;\n"
    "    hideTyping();if(typewriterActive)finishTypewriter();\n"
    "    if(sendPing){clearInterval(sendPing);sendPing=null;}\n"
    "    if(pongTimer){clearTimeout(pongTimer);pongTimer=null;}\n"
    "    if(msgTimer){clearTimeout(msgTimer);msgTimer=null;}\n"
    "    ws=null;\n"
    "    scheduleReconnect();\n"
    "  };\n"
    "\n"
    "  // @用途 WebSocket 错误回调\n"
    "  // @说明 清理后触发重连\n"
    "  ws.onerror=function(){\n"
    "    clearTimeout(connTimeout);\n"
    "    setStatus('red');\n"
    "    if(ws){ws.onclose=null;ws.close();ws=null;}\n"
    "    scheduleReconnect();\n"
    "  };\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 指数退避重连调度\n"
    " * @说明 每次重连间隔递增: 1s → 2s → 4s → 8s → 16s → 30s(上限)\n"
    " *        无限重试, 不设次数上限\n"
    " */\n"
    "function scheduleReconnect(){\n"
    "  if(reconnTimer)return;\n"
    "  reconnCount++;\n"
    "  const delay=Math.min(1000*Math.pow(2,Math.min(reconnCount-1,5)),30000);\n"
    "  setStatus('yellow');\n"
    "  reconnTimer=setTimeout(connect,delay);\n"
    "}\n"
    "\n"
    "// ========================== 消息渲染 ==========================\n"
    "let pendingMsgs=[];\n"
    "\n"
    "/**\n"
    " * @用途 添加一条消息到聊天区\n"
    " * @参数 type {string} 'user' | 'ai' | 'system'\n"
    " * @参数 text {string} 消息正文\n"
    " * @说明 AI 消息触发打字机效果, 其他类型立即渲染\n"
    " *        第一条消息发送后切换空状态→聊天模式\n"
    " */\n"
    "function addMsg(type,text){\n"
    "  if(type==='ai'){startTypewriter(text);return;}\n"
    "  if(!hasSent){hasSent=true;mainEl.classList.add('chatting');}\n"
    "  const row=document.createElement('div');\n"
    "  row.className='msg '+type;\n"
    "  const bub=document.createElement('div');\n"
    "  bub.className='bubble';\n"
    "  bub.innerHTML=(type==='user'?escapeHtml(text):renderMarkdown(text));\n"
    "  const t=document.createElement('span');\n"
    "  t.className='time';t.textContent=timeStr();\n"
    "  bub.appendChild(t);row.appendChild(bub);\n"
    "  msgArea.appendChild(row);\n"
    "  msgCount++;\n"
    "  if(atBottom)scrollBottom();\n"
    "  if(type!=='system')saveMsg(type,text);\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 添加一条系统提示消息 (居中灰色小字)\n"
    " * @参数 text {string} 提示文本\n"
    " */\n"
    "function addSystem(text){\n"
    "  const row=document.createElement('div');\n"
    "  row.className='msg system';\n"
    "  const bub=document.createElement('div');\n"
    "  bub.className='bubble';bub.textContent=text;\n"
    "  row.appendChild(bub);\n"
    "  msgArea.appendChild(row);\n"
    "  if(atBottom)scrollBottom();\n"
    "  saveMsg('system',text);\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 添加一条 LLM 错误消息 (红色边框 + 错误图标)\n"
    " * @参数 text {string} 错误描述文本\n"
    " */\n"
    "function addError(text){\n"
    "  hideTyping();\n"
    "  if(msgTimer){clearTimeout(msgTimer);msgTimer=null;}\n"
    "  const row=document.createElement('div');\n"
    "  row.className='msg error';\n"
    "  const bub=document.createElement('div');\n"
    "  bub.className='bubble';bub.innerHTML=text;\n"
    "  row.appendChild(bub);\n"
    "  msgArea.appendChild(row);\n"
    "  if(atBottom)scrollBottom();\n"
    "  saveMsg('system',text);\n"
    "}\n"
    "\n"
    "// ========================== 打字动画 (带 AI思考中 状态文字) ==========================\n"
    "/**\n"
    " * @用途 显示 AI 思考中的状态: \"AI思考中...\" + 三点弹跳动画\n"
    " * @说明 用户发送消息后调用, 同时启动 30s 请求超时计时器\n"
    " *        收到 AI 回复时 hideTyping() 移除\n"
    " */\n"
    "function showTyping(){\n"
    "  if(typingEl)return;\n"
    "  // 启动 30s 请求超时计时器\n"
    "  if(msgTimer){clearTimeout(msgTimer);msgTimer=null;}\n"
    "  msgTimer=setTimeout(function(){\n"
    "    hideTyping();\n"
    "    addError('⚠️ 请求超时，请重试');\n"
    "  },30000);\n"
    "  typingEl=document.createElement('div');\n"
    "  typingEl.className='msg ai';\n"
    "  typingEl.innerHTML='<div class=\"typing\"><span class=\"text\">AI思考中</span><span class=\"dots\"><span></span><span></span><span></span></span></div>';\n"
    "  msgArea.appendChild(typingEl);if(atBottom)scrollBottom();\n"
    "}\n"
    "function hideTyping(){\n"
    "  if(msgTimer){clearTimeout(msgTimer);msgTimer=null;}\n"
    "  if(typingEl){typingEl.remove();typingEl=null;}\n"
    "}\n"
    "\n"
    "// ========================== 打字机效果 ==========================\n"
    "let typewriterTimer=null,typewriterRow=null,typewriterBub=null;\n"
    "let typewriterIdx=0,typewriterRaw='';\n"
    "\n"
    "/**\n"
    " * @用途 逐字追加 AI 回复文本, 模拟打字效果\n"
    " * @参数 text {string} AI 回复原文 (纯文本)\n"
    " * @说明 先以 raw text 逐字填入, 完成后替换为 Markdown 渲染版\n"
    " *        速度: 长文本(>200字符) 8ms/步, 短文本 16ms/步\n"
    " */\n"
    "function startTypewriter(text){\n"
    "  if(!text)return;\n"
    "  stopTypewriter();\n"
    "  if(!hasSent){hasSent=true;mainEl.classList.add('chatting');}\n"
    "  typewriterActive=true;typewriterRaw=text;\n"
    "  const escaped=escapeHtml(text);\n"
    "  hideTyping();\n"
    "  typewriterRow=document.createElement('div');\n"
    "  typewriterRow.className='msg ai';\n"
    "  typewriterBub=document.createElement('div');\n"
    "  typewriterBub.className='bubble';\n"
    "  typewriterBub.innerHTML='<span class=\"md\"></span><span class=\"cursor\"></span>';\n"
    "  const t=document.createElement('span');t.className='time';t.textContent=timeStr();\n"
    "  typewriterBub.appendChild(t);\n"
    "  typewriterRow.appendChild(typewriterBub);\n"
    "  msgArea.appendChild(typewriterRow);msgCount++;\n"
    "  if(atBottom)scrollBottom();\n"
    "  setTimeout(()=>t.style.opacity='1',800);\n"
    "  typewriterIdx=0;\n"
    "  const speed=text.length>200?8:16;\n"
    "  typewriterTimer=setInterval(function(){\n"
    "    if(typewriterIdx>=escaped.length){finishTypewriter();return;}\n"
    "    typewriterIdx=Math.min(typewriterIdx+3,escaped.length);\n"
    "    typewriterBub.querySelector('.md').textContent=escaped.substring(0,typewriterIdx);\n"
    "    if(atBottom)scrollBottom();\n"
    "  },speed);\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 完成打字机效果, 替换为 Markdown 渲染内容\n"
    " */\n"
    "function finishTypewriter(){\n"
    "  if(!typewriterActive)return;\n"
    "  typewriterActive=false;\n"
    "  if(typewriterTimer){clearInterval(typewriterTimer);typewriterTimer=null;}\n"
    "  const md=typewriterBub.querySelector('.md');\n"
    "  const cur=typewriterBub.querySelector('.cursor');\n"
    "  if(md)md.innerHTML=renderMarkdown(typewriterRaw);\n"
    "  if(cur)cur.remove();\n"
    "  saveMsg('ai',typewriterRaw);\n"
    "  typewriterRow=null;typewriterBub=null;typewriterRaw='';\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 立即停止打字机效果 (用于清空/重连等场景)\n"
    " */\n"
    "function stopTypewriter(){\n"
    "  if(typewriterTimer){clearInterval(typewriterTimer);typewriterTimer=null;}\n"
    "  typewriterActive=false;\n"
    "  if(typewriterBub){const c=typewriterBub.querySelector('.cursor');if(c)c.remove();}\n"
    "  typewriterRow=null;typewriterBub=null;typewriterRaw='';\n"
    "}\n"
    "\n"
    "// ========================== Markdown 渲染 ==========================\n"
    "/**\n"
    " * @用途 将纯文本中的 Markdown 语法转换为 HTML\n"
    " * @参数 t {string} 已 HTML 转义后的文本\n"
    " * @返回 {string} 渲染后的 HTML\n"
    " * @说明 支持: 代码块(```) / 行内代码(`) / 粗体(** __) / 斜体(* _)\n"
    " *        链接([text](url)) / 无序列表(- *) / 有序列表(1.) / 换行(\\n→<br>)\n"
    " */\n"
    "function renderMarkdown(t){\n"
    "  // 代码块: ```lang\\ncode``` → <pre><code>\n"
    "  t=t.replace(/```(\\w*)\\n?([\\s\\S]*?)```/g,function(_,l,c){return '<pre><code>'+escapeHtml(c.trim())+'</code></pre>';});\n"
    "  t=t.replace(/`([^`]+)`/g,'<code>$1</code>');\n"
    "  t=t.replace(/\\*\\*(.+?)\\*\\*/g,'<strong>$1</strong>');\n"
    "  t=t.replace(/__(.+?)__/g,'<strong>$1</strong>');\n"
    "  t=t.replace(/\\*(.+?)\\*/g,'<em>$1</em>');\n"
    "  t=t.replace(/_(.+?)_/g,'<em>$1</em>');\n"
    "  t=t.replace(/\\[([^\\]]+)\\]\\(([^)]+)\\)/g,'<a href=\"$2\" target=\"_blank\" rel=\"noopener\">$1</a>');\n"
    "  t=t.replace(/^[\\s]*[-*]\\s+(.+)$/gm,'<li>$1</li>');\n"
    "  t=t.replace(/((?:<li>.*<\\/li>\\n?)+)/g,'<ul>$1</ul>');\n"
    "  t=t.replace(/^[\\s]*\\d+\\.\\s+(.+)$/gm,'<li>$1</li>');\n"
    "  t=t.replace(/((?:<li>.*<\\/li>\\n?)+)(?!\\s*<\\/(?:ul|ol)>)/g,function(m){return m.includes('<ul>')||m.includes('<ol>')?m:'<ol>'+m+'</ol>';});\n"
    "  t=t.replace(/\\n/g,'<br>');\n"
    "  return t;\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 HTML 实体转义, 防止 XSS\n"
    " * @参数 str {string} 原始文本\n"
    " * @返回 {string} 转义后的文本\n"
    " */\n"
    "function escapeHtml(str){\n"
    "  const m={'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'};\n"
    "  return str.replace(/[&<>\"']/g,c=>m[c]);\n"
    "}\n"
    "\n"
    "// ========================== 快捷发送 (推荐卡片) ==========================\n"
    "/**\n"
    " * @用途 点击推荐卡片时自动填入并发送\n"
    " * @参数 text {string} 要发送的文本\n"
    " */\n"
    "function quickSend(text){\n"
    "  msgInput.value=text;sendMessage();\n"
    "}\n"
    "\n"
    "// ========================== 消息发送 ==========================\n"
    "/**\n"
    " * @用途 发送消息主入口\n"
    " * @说明 先检查 / 前缀指令, 然后显示打字动画并通过 WebSocket 发送\n"
    " *        未连接时消息入 pending 队列, 连接恢复后自动补发\n"
    " */\n"
    "function sendMessage(){\n"
    "  const text=msgInput.value.trim();\n"
    "  if(!text)return;\n"
    "  msgInput.value='';msgInput.style.height='auto';\n"
    "  // 检查 / 前缀系统指令\n"
    "  if(text.startsWith('/')){\n"
    "    const sp=text.indexOf(' ');const cmd=sp>0?text.substring(1,sp).toLowerCase():text.substring(1).toLowerCase();\n"
    "    const arg=sp>0?text.substring(sp+1).trim():'';\n"
    "    if(execCmd(cmd,arg))return;\n"
    "  }\n"
    "  addMsg('user',text);\n"
    "  showTyping();  // 显示 \"AI思考中...\" + 启动 30s 超时计时器\n"
    "  if(!connected||!ws){pendingMsgs.push(text);addSystem('消息已暂存');return;}\n"
    "  try{ws.send(text);}catch(e){pendingMsgs.push(text);addSystem('发送失败');}\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 处理 / 前缀系统指令\n"
    " * @参数 cmd {string} 指令名 (小写)\n"
    " * @参数 arg {string} 指令参数 (可能为空)\n"
    " * @返回 {boolean} true=已处理 / false=未匹配\n"
    " * @支持指令:\n"
    " *   /help         显示帮助信息\n"
    " *   /clear        清空对话\n"
    " *   /model <名>   设置 LLM 模型名\n"
    " *   /provider <名>设置 LLM 提供商\n"
    " *   /key <密钥>   设置 LLM API Key\n"
    " *   /wifi         查看 WiFi 状态 (转发到固件)\n"
    " *   /status       查看系统状态 (转发到固件)\n"
    " *   /ping         测试 WebSocket 连接\n"
    " */\n"
    "function execCmd(cmd,arg){\n"
    "  switch(cmd){\n"
    "    case 'help':addMsg('ai','可用指令: /key /model /provider /wifi /status /clear /ping');return true;\n"
    "    case 'clear':clearChat();return true;\n"
    "    case 'model':if(arg){sendRaw('llm_model '+arg);cfgModel=arg;updateModelHint();saveConfig();addSystem('✓ 模型: '+arg);}else addSystem('用法: /model <模型名>');return true;\n"
    "    case 'provider':if(arg){sendRaw('llm_provider '+arg);cfgProvider=arg;saveConfig();addSystem('✓ 提供商: '+arg);}else addSystem('用法: /provider <名称>');return true;\n"
    "    case 'key':if(arg){sendRaw('llm_key '+arg);cfgApiKey=true;saveConfig();addSystem('✓ API Key 已设置');}else addSystem('用法: /key <API Key>');return true;\n"
    "    case 'wifi':sendRaw('wifi_status');return true;\n"
    "    case 'status':sendRaw('status');return true;\n"
    "    case 'ping':addSystem('pong');return true;\n"
    "    default:addSystem('未知指令 /'+cmd+'  /help 查看帮助');return true;\n"
    "  }\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 通过 WebSocket 发送原始文本 (用于系统指令)\n"
    " * @参数 text {string} 要发送的文本\n"
    " * @说明 未连接时入 pending 队列\n"
    " */\n"
    "function sendRaw(text){\n"
    "  if(!connected||!ws){pendingMsgs.push(text);return;}\n"
    "  try{ws.send(text);}catch(e){pendingMsgs.push(text);}\n"
    "}\n"
    "\n"
    "// ========================== 配置持久化 (localStorage) ==========================\n"
    "const CFG_KEY='mimi_web_config';\n"
    "\n"
    "/**\n"
    " * @用途 保存 LLM 配置到 localStorage\n"
    " * @说明 存储 provider / model / apikey 三个字段\n"
    " */\n"
    "function saveConfig(){\n"
    "  try{localStorage.setItem(CFG_KEY,JSON.stringify({provider:cfgProvider,model:cfgModel,apikey:cfgApiKey}));}catch(e){}\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 从 localStorage 恢复 LLM 配置\n"
    " * @说明 页面刷新后自动恢复上一次的模型/提供商设置\n"
    " */\n"
    "function loadConfig(){\n"
    "  try{\n"
    "    const d=JSON.parse(localStorage.getItem(CFG_KEY));\n"
    "    if(d){\n"
    "      if(d.provider)cfgProvider=d.provider;\n"
    "      if(d.model){cfgModel=d.model;updateModelHint();}\n"
    "      if(d.apikey)cfgApiKey=true;\n"
    "    }\n"
    "  }catch(e){}\n"
    "}\n"
    "\n"
    "// ========================== 消息持久化 (localStorage) ==========================\n"
    "const STORAGE_KEY='mimi_chat_msgs';\n"
    "\n"
    "/**\n"
    " * @用途 保存一条聊天记录到 localStorage\n"
    " * @参数 type {string} 'user' | 'ai' | 'system'\n"
    " * @参数 content {string} 消息内容\n"
    " * @说明 上限 200 条, 超出时删除最旧的\n"
    " */\n"
    "function saveMsg(type,content){\n"
    "  try{\n"
    "    let msgs=JSON.parse(localStorage.getItem(STORAGE_KEY))||[];\n"
    "    msgs.push({type,content,time:timeStr()});\n"
    "    if(msgs.length>200)msgs=msgs.slice(-200);\n"
    "    localStorage.setItem(STORAGE_KEY,JSON.stringify(msgs));\n"
    "  }catch(e){}\n"
    "}\n"
    "\n"
    "/**\n"
    " * @用途 页面加载时从 localStorage 恢复聊天记录\n"
    " * @说明 从旧到新依次重建消息 DOM, 自动滚动到底部\n"
    " */\n"
    "function loadMessages(){\n"
    "  try{\n"
    "    const msgs=JSON.parse(localStorage.getItem(STORAGE_KEY));\n"
    "    if(!msgs||!msgs.length)return;\n"
    "    for(const m of msgs){\n"
    "      if(m.type==='system'){\n"
    "        const row=document.createElement('div');row.className='msg system';\n"
    "        const b=document.createElement('div');b.className='bubble';b.textContent=m.content||'';\n"
    "        row.appendChild(b);msgArea.appendChild(row);\n"
    "      }else{\n"
    "        const row=document.createElement('div');row.className='msg '+m.type;\n"
    "        const b=document.createElement('div');b.className='bubble';\n"
    "        b.innerHTML=(m.type==='user'?escapeHtml(m.content||''):renderMarkdown(m.content||''));\n"
    "        const t=document.createElement('span');t.className='time';t.textContent=m.time||'';\n"
    "        t.style.opacity='1';b.appendChild(t);row.appendChild(b);\n"
    "        msgArea.appendChild(row);\n"
    "      }\n"
    "      msgCount++;\n"
    "    }\n"
    "    if(msgs.length){hasSent=true;mainEl.classList.add('chatting');scrollBottom();}\n"
    "  }catch(e){}\n"
    "}\n"
    "\n"
    "// ========================== 新建 / 清空对话 ==========================\n"
    "/**\n"
    " * @用途 清空聊天记录并恢复空状态\n"
    " * @说明 清除 localStorage、DOM、状态变量, 回到欢迎页面\n"
    " */\n"
    "function newChat(){\n"
    "  msgArea.innerHTML='';msgCount=0;hasSent=false;\n"
    "  mainEl.classList.remove('chatting');\n"
    "  hideTyping();if(typewriterActive)stopTypewriter();\n"
    "  try{localStorage.removeItem(STORAGE_KEY);}catch(e){}\n"
    "}\n"
    "\n"
    "function clearChat(){newChat();}\n"
    "\n"
    "// ========================== 输入框事件 ==========================\n"
    "// auto-resize: 随内容自动扩展高度, 上限 200px\n"
    "msgInput.addEventListener('input',function(){\n"
    "  this.style.height='auto';\n"
    "  this.style.height=Math.min(this.scrollHeight,200)+'px';\n"
    "});\n"
    "// Enter 发送, Shift+Enter 换行\n"
    "msgInput.addEventListener('keydown',function(e){\n"
    "  if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage();}\n"
    "});\n"
    "\n"
    "// ========================== 初始化 ==========================\n"
    "loadConfig();          // 恢复 LLM 配置\n"
    "loadMessages();        // 恢复聊天记录\n"
    "// 重置连接状态并立即发起 WebSocket 连接\n"
    "reconnCount=0;\n"
    "if(reconnTimer){clearTimeout(reconnTimer);reconnTimer=null;}\n"
    "if(ws){ws.onclose=null;ws.close();ws=null;}\n"
    "connect();\n"
    "})();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "\n"
;

#endif /* WEB_UI_H */
